### ISSUE TITLE
HTML5 forms must be able to process workflow rules

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#100]
We need to be able to process workflow rules for HTML5 forms.  This will entail the following:

1. Check to see if workflow is enabled on the PSI.  If so, process workflow rules.  Otherwise, save the form and go to the stage.
1. Update code that evaluates the PSI against the workflow rules.  This will most likely entail somehow getting the JSON PSI converted to a `PageSetInstance` POJO.  The code in `WizardWorkflowDefinitionBuilder` and `WizardRuleEvaluator` will most likely be fine since they work on the PSI POJO.  We may have to add a new method to RESTWizardWorkflow - `evaluateJsonPsiWorkflowRules`? - basically, take the JSON and build a `PageSetInstance` POJO - new method in `PSIUtil`, then call `WizardWorkflowDefinitionBuilder` as before.
1. Build a workflow summary page into the HTML5 active wizard form
  - Only show the page if the form uses workflow (determined by a checkbox in the AW admin)
  - Display roles grouped by activity (like the Flex version)
1. Ensure that workflow review and approval routes can be completed in Activiti (ignore attached workflow docs for now).

**Comment by mikeblum** [comment]
Revision: 11415
Author: mblum
Date: 2014-12-30 11:59:10.925219
merging in workflow docs feature branch ***OC Update required***

A	/trunk/code/app/modules/actions/manageworkflowdocuments.js (Copied from  11370)
M	/trunk/code/app/modules/actions/createwizardform.js
M	/trunk/code/app/modules/wizard/models/wizardcontext.js
M	/trunk/code/app/modules/actions/managerelations.js
M	/trunk/code/app/modules/common/typeahead.js
M	/trunk/code/app
M	/trunk/code
M	/trunk/code/assets/css/styles/actions/manageRelations.styl
A	/trunk/code/app/modules/conditions (Copied from  11414)
M	/trunk/code/test/tests
A	/trunk/code/test/tests/modules/conditions (Copied from  11414)
M	/trunk/code/app/modules/wizard/activeformrouter.js
M	/trunk/code/app/templates/actions/managerelations/addrelations.html
M	/trunk/code/app/templates/actions/managerelations/existingrelations.html
M	/trunk/code/app/configs/config-actions.js
