### ISSUE TITLE
Include Exit and Save and Exit Functionality

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#101]
Users should be able to:

- exit - cancel checkout and go back to the stage
- save and exit - checkin changes (or create the PSI) and go back to the stage

We should be especially careful in testing save and exit scenarios.  For example, 

**Base Testing**
1. User partially fills out a form and saves/exits
1. Upon going back to the form:
  - Nice to have - send the user where they left off
  - What flex does - send the user to the first page

**Complex Testing**
1. User partially fills out a form including adding some supporting documents
1. User saves/exits
1. Documents should be uploaded to the repo
1. User edits the form and:
  - adds more documents
  - removes some documents from the first edt and adds more
  - removes the file question from the question flow
1. After finishing (or save/exit), the correct documents should be in the repo.  Orphaned documents should be cleaned up

See also: #90

**Comment by gsteimer** [comment]
No - we have "Save and Exit" (ie - checkin), but we don't yet have "Exit" (ie - Cancel Checkout)

**Comment by b-k-white** [comment]
Changed the resumeForm route to now checkout the form when editing so that multiple users can't edit at the same time. Also added the cancelAndExit route which cancels the checkout and does not save any of the changes made to the form.
CR - Blum
HPI_REV - 11475

**Comment by gsteimer** [comment]
Exit does not work on Edge1 or Edge2.  See the screencam below.

![exit-form](https://cloud.githubusercontent.com/assets/1377228/5723428/85fdc996-9b09-11e4-82f5-defd6f3ef6d9.gif)

It looks like the issue is that on both, an extra `/hpi` is put in the URL.  However, when I take it out of the Edge2 URL, it 404s for some reason.

@mikeblum @dgrumieaux - this will be high priority to fix for your project if you want to use HTML5.

**Comment by gsteimer** [comment]
@mikeblum - this works for existing forms in your latest commit, but blows up when you create a new form and exit:

![exit-before-save](https://cloud.githubusercontent.com/assets/1377228/5724602/5badc2e6-9b12-11e4-98c6-5d425b21aebb.gif)

@dgrumieaux and I talked about either sending the user back to the first non-stage URL in their history, or if that's difficult, always send the user back to the Dashboard.

**Comment by mikeblum** [comment]
can this be closed?

**Comment by gsteimer** [comment]
Yeah, this looks good now on edge
