### ISSUE TITLE
Ability to lead from a query-generated answer

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#105]
In the flex module, it was possible to lead from a query generated answer using the Leading Page Value Criteria field:

![image](https://cloud.githubusercontent.com/assets/1377228/5001496/f5f84ba6-69bb-11e4-88b9-568ab05dcf67.png)

Basically - the leading action was placed on the query placeholder answer and would only be processed if the value of the selected answer matched the value entered in the admin.

**Comment by renesaladrigas** [comment]
LEADING RULE - Adding support to leading rule criteria values. Configuring a criteria value on a leading rule will take precedence in the equality check to determine if we are going to a new page, then defaulting to checking if the value is equal to the hard coded answer value. Fixes GH issues: https://github.com/tsgrp/HPI/issues/1797 and https://github.com/tsgrp/ActiveWizard/issues/105

CR - nquillin, gsinger
rev - 22571
