### ISSUE TITLE
Support Sectional Lockdown

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#110]
Support the sectional lockdown feature in HTML5 Active Form.  This feature basically locked down certain pages in the form during the approval route.  Only users in a configured role can edit the page.  Everyone else sees the page as read-only.

Talk to @benallenallen @dhartman25 and me before starting this one.

**Comment by gsteimer** [comment]
@mikeblum - correct me if I'm wrong, but did this go in with the fixes for #265?

**Comment by gsteimer** [comment]
Testing on edge1 with `TS Sectional Lockdown` - it looks like when a page is open to any role, I am still locked out of the page:

![image](https://cloud.githubusercontent.com/assets/1377228/10523429/0fdbd798-7340-11e5-80a8-47958d811e89.png)

I'm logged in as the 'AW admin' approver that can edit page 1.

**Comment by gsteimer** [comment]
As in #267, I cannot finish a form in the approval route:

![image](https://cloud.githubusercontent.com/assets/1377228/10523481/3ba36652-7340-11e5-985f-97627a17c773.png)

**Comment by mikeblum** [comment]
Revision: 13369
Author: mblum
Date: Tuesday, October 13, 2015 4:29:25 PM
Message:

## SECTIONAL LOCKDOWN: support for disabling all the control types for the Wizard and the various Sectional Lockdown scenarios.

Modified : /trunk/code
Modified : /trunk/code/app
Modified : /trunk/code/app/modules/common/tossacross.js
Modified : /trunk/code/app/modules/wizard/activeform.js
Modified : /trunk/code/app/modules/wizard/activeformrouter.js
Modified : /trunk/code/app/modules/wizard/formfields/aspects.js
Modified : /trunk/code/app/modules/wizard/formfields/fieldfactory.js
Added : /trunk/code/app/modules/wizard/formfields/temporaryaspects.js (Copy from path: /feature_branches/wizard_sectional_lockdown/app/modules/wizard/formfields/temporaryaspects.js, Revision, 13320)
Modified : /trunk/code/app/modules/wizard/models/field.js
Modified : /trunk/code/app/modules/wizard/models/page.js
Modified : /trunk/code/app/modules/wizard/models/pagesetinstance.js
Modified : /trunk/code/app/modules/wizard/services/pagesetinstanceprovider.js
Added : /trunk/code/app/modules/wizard/services/sectionallockdownservice.js (Copy from path: /feature_branches/wizard_sectional_lockdown/app/modules/wizard/services/sectionallockdownservice.js, Revision, 13320)
Modified : /trunk/code/app/modules/wizard/views/abstractcontrol.js
Modified : /trunk/code/app/modules/wizard/views/controltypes.js
Modified : /trunk/code/app/modules/wizard/views/flowpathview.js
Modified : /trunk/code/app/modules/wizard/views/navigationcontrolsview.js
Modified : /trunk/code/app/modules/wizard/views/pagesetinstanceview.js
Modified : /trunk/code/app/modules/wizard/views/pageview.js
Modified : /trunk/code/app/modules/wizard/views/psiheaderview.js
Modified : /trunk/code/app/modules/wizard/views/summaryview.js
Modified : /trunk/code/app/templates/common/tossacross/filter.html
Modified : /trunk/code/app/templates/common/tossacross/item.html
Modified : /trunk/code/app/templates/common/tossacross/tossacross-mainlayout.html
Modified : /trunk/code/app/templates/formfields/checkboxescontrol.html
Modified : /trunk/code/app/templates/formfields/datepicker.html
Modified : /trunk/code/app/templates/formfields/radiocontrol.html
Modified : /trunk/code/app/templates/search/quicksearch.html
Modified : /trunk/code/app/templates/wizard/psi-header.html
Modified : /trunk/code/app/templates/wizard/tablequestiongroupcontrols.html
Modified : /trunk/code/app/templates/wizard/verticalquestiongroupcontrols.html
Modified : /trunk/code/app/templates/wizard/wyswigcontrol.html
Modified : /trunk/code/assets/css/styles/hpi.styl
Modified : /trunk/code/project
Modified : /trunk/code/test/tests
Modified : /trunk/code/test/tests/modules/wizard/formfields/formfieldsSpec.js
Modified : /trunk/code/test/tests/modules/wizard/services/pagesetinstanceproviderSpec.js
Added : /trunk/code/test/tests/modules/wizard/services/sectionallockdownserviceSpec.js (Copy from path: /feature_branches/wizard_sectional_lockdown/test/tests/modules/wizard/services/sectionallockdownserviceSpec.js, Revision, 13320)
Modified : /trunk/code/test/tests/modules/wizard/wizard/views/navigationcontrolsviewSpec.js

---

r13549 | mblum | 2015-10-26 13:22:37 -0500 (Mon, 26 Oct 2015) | 1 line
Changed paths:
   M /trunk/code/app/modules/wizard/services/sectionallockdownservice.js

SECTIONAL LOCKDOWN: wording change for pages locked down by other pages in a Wizard form

See #265 for the commits related to disabling controls.
