### ISSUE TITLE
Question Group - Ability to Reorder

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#112]
Users should be able to reorder rows in our repeating question group (table view or mobile view).

**Comment by mikeblum** [comment]
Revision: 11431
Author: mblum
Date: Monday, January 05, 2015 3:13:59 PM
Message:
merging in sortable question groups in the wizard: https://github.com/tsgrp/ActiveWizard/issues/112
----
Modified : /trunk/code
Modified : /trunk/code/app
Modified : /trunk/code/app/app.js
Modified : /trunk/code/app/configs/config-core.js
Modified : /trunk/code/app/modules/actions/createwizardform.js
Modified : /trunk/code/app/modules/wizard/models/questioncollection.js
Modified : /trunk/code/app/modules/wizard/views/pageview.js
Added : /trunk/code/app/templates/wizard/sortable.html (Copy from path: /feature_branches/wizard_sortable_question_groups/app/templates/wizard/sortable.html, Revision, 11430)
Modified : /trunk/code/assets/css/styles/wizard.styl
Added : /trunk/code/assets/js/plugins/jquery.ui.touch-punch.js (Copy from path: /feature_branches/wizard_sortable_question_groups/assets/js/plugins/jquery.ui.touch-punch.js, Revision, 11430)
Modified : /trunk/code/test/tests
Added : /trunk/code/test/tests/actions/createwizardformSpec.js (Copy from path: /feature_branches/wizard_sortable_question_groups/test/tests/actions/createwizardformSpec.js, Revision, 11430)
