### ISSUE TITLE
Calculation Precision

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#115]
Calculations should support the "precision" configuration in the Wizard admin:

![image](https://cloud.githubusercontent.com/assets/1377228/5134104/a797d2f8-70d0-11e4-8cb5-a7378bd27c1d.png)

So for example, if you have a calculation that's trying to execute `100 / 3`, and the calculation precision is set to 2, the result should be `33.33`, not `33.3333333`.

**Comment by mikeblum** [comment]
Revision: 11420
Author: mblum
Date: 2015-01-02 13:03:40.472094
CALCULATION PRECISION: closing https://github.com/tsgrp/ActiveWizard/issues/115. unit tests test precision checks

M	/trunk/code/app/modules/wizard/services/formulaservice.js
M	/trunk/code/app/modules/wizard/models/question.js
M	/trunk/code/test/tests/modules/wizard/services/formulaserviceSpec.js
