### ISSUE TITLE
Repeating Table - Look and Feel

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#121]
See the screenshot below.  Too much weight is given to dropdowns.  In the case below, I have three dropdowns and two textboxes.  The textboxes are way too small, and the dropdowns are bigger than necessary.

![image](https://cloud.githubusercontent.com/assets/1377228/5187436/beb3ba36-7492-11e4-9d7a-5e1e1618ce33.png)

**Comment by mikeblum** [comment]
Revision: 11486
Author: mblum
Date: 2015-01-12 10:30:57.906734
WIZARD TABLE STYLING: fix for typeahead styling/controls in active form tables. Tested in IE and Chrome mobile/desktop. https://github.com/tsgrp/ActiveWizard/issues/121

M	/trunk/code/app/templates/wizard/verticalquestiongrouptable.html
M	/trunk/code/assets/css/styles/wizard.styl
M	/trunk/code/app/templates/wizard/table.html

**Comment by gsteimer** [comment]
This looks better, especially when no data is in the table.  However, the padding still looks off, especially around the "move" icon.  Also note that we've been trying to use a different icon for dragging and dropping rows in HPI.  Please change the icon to `glyphicon-sort`

**Before Adding Rows**
![image](https://cloud.githubusercontent.com/assets/1377228/5723922/81d4ad2c-9b0d-11e4-8bbe-f809c0c211ed.png)

**After Adding Rows - Table**
![image](https://cloud.githubusercontent.com/assets/1377228/5723940/a4a165f2-9b0d-11e4-8949-bb54876cf4a2.png)

**After Adding Rows - Mobile**
![image](https://cloud.githubusercontent.com/assets/1377228/5723948/add4d80c-9b0d-11e4-9912-81bd48261fa7.png)

**Comment by gsteimer** [comment]
@mikeblum - table view looks much better, but the spacing on the left when there's more than one row is off.  There's way too much wasted space:

![image](https://cloud.githubusercontent.com/assets/1377228/6394815/b9148fd8-bd99-11e4-9354-cca08ae6d162.png)

**Comment by gsteimer** [comment]
Note the same thing in narrow view:

![image](https://cloud.githubusercontent.com/assets/1377228/6394837/d384b8e8-bd99-11e4-9689-d98dfc5772a7.png)

**Comment by gsteimer** [comment]
Also - notice how there's a ton of wasted space above the table too:

![image](https://cloud.githubusercontent.com/assets/1377228/6396148/738e3280-bda2-11e4-9d87-641fb64b5800.png)

**Comment by gsteimer** [comment]
Another one - when the table is just one field (in this case it's a textarea), there's also a ton of wasted space on the right side when there's more than one row:

1 row looks great:
![image](https://cloud.githubusercontent.com/assets/1377228/6396177/9dc679a4-bda2-11e4-8466-4b2317464aac.png)

2 rows, not so much:
![image](https://cloud.githubusercontent.com/assets/1377228/6396185/a68b2ba2-bda2-11e4-86b5-83679acb710f.png)

**Comment by gsteimer** [comment]
I'm still seeing issues in the release environment with too much width on the left side when there's more than one row in the table:

![image](https://cloud.githubusercontent.com/assets/1377228/7545162/1b3f8fa0-f599-11e4-94e5-76bccd5d293a.png)

**Comment by gsteimer** [comment]
Another oddity.  With the latest code, the table does look better when there's more than one (in desktop view):

![image](https://cloud.githubusercontent.com/assets/1377228/7889988/97f7d776-0608-11e5-9773-5f41454a3ce9.png)

However, when you try to reorder rows, things look messed up:

![image](https://cloud.githubusercontent.com/assets/1377228/7889998/abb30a2e-0608-11e5-9c6b-b4911ba1b8b0.png)

I'm noticing that:
- [x] Everything gets pushed to the right and a ton of whitespace is on the left
- [x] The dragged row has all fields blanked out
- [x] The dragged row hangs off the side on the right of the table

**Comment by mikeblum** [comment]
I at one point saw a cataloged issue with bootstrap and drag & dropping
rows. I know the visual hiccup happens during the drag but fixes itself
after releasing the row. Is this still the case?

**Comment by gsteimer** [comment]
Yes - when you drop the row, it's fine.  It's just during the drag that it looks messed up

**Comment by mikeblum** [comment]
Found the reference I based my original fix on:
http://stackoverflow.com/questions/8599922/jquery-sortable-plugin-on-table-cells-shrink-while-dragging.
Maybe all we need to do is tweak the styling of the helper function?

**Comment by grahamsinger** [comment]
Fixed with revision 12652.

The reason why the fields were blanking out was because a whole new view is created when you start dragging.  And, because these are `input` and `select` tags, simply copying the markup (as was being done before) doesn't work.  To fix it, I just mapped out the values and the views so that when that new "row" view is created, it puts the existing values in the draggable view.

Also, fixed the styling so that the new view doesn't hang off the page, however there is still a tad bit of offset caused by the drag glyphicon.  It seems to be bootstraps auto adjusting of tables that is causing that.

CR: MB

**Comment by gsteimer** [comment]
@grahamsinger - were you able to remove the wasted white space on the top and left?

**Comment by grahamsinger** [comment]
@gsteimer for top, do you mean above the entire table?

**Comment by grahamsinger** [comment]
Fixed spacing at top with revision 12653.

Still spacing issues in the rows whenever the sorting glyphicon gets added (i.e. when there is more than one row).

**Comment by gsteimer** [comment]
The table looks a lot better, thanks for the updates.  A couple of quirks:

It looks like it's possible to order a row completely below the 'add new' button:
![image](https://cloud.githubusercontent.com/assets/1377228/8575175/3a0eac94-2560-11e5-896e-ec065616e2af.png)

For some reason, textboxes show their required error message when the page is loaded.  Causes the table to look out of alignment:
![image](https://cloud.githubusercontent.com/assets/1377228/8575300/e20e64de-2560-11e5-9796-1b8a9e90296d.png)

**Comment by gsteimer** [comment]
It looks like something changed where reordering a table row causes the row to completely disappear until it is dropped:

![table-view-laf](https://cloud.githubusercontent.com/assets/1377228/14891308/ca08c4f2-0d2b-11e6-870c-97102aa6f032.gif)

It also looks like something changed with the styling of the remove row button.  That icon seems to not be vertically aligned properly.

**Comment by gsteimer** [comment]
Fixed in HPI 2.5
