### ISSUE TITLE
Supporting Documents - Uploaded supporting docs should be deleted if their question group row is De

### ISSUE THREAD

**Issue by aviking** [tsgrp/ActiveWizard#137]
When you have supporting docs uploaded on a form in a question group where they are not the first row and they are already stored in the repository, if you click on the trash can which deletes the row, the supporting docs should be deleted from the repository and not exist. See the gif.

![trachcanshoulddeletedocs](https://cloud.githubusercontent.com/assets/2895070/5306509/9cb57976-7bca-11e4-81d2-8972df6900c2.gif)

**Comment by mikeblum** [comment]
elevating to high priority as this will affect our current project.

**Comment by gsteimer** [comment]
@mikeblum - before starting on the design on this one, we should have a high level design review with  @benallenallen and me

**Comment by mikeblum** [comment]
Revision: 11659
Author: mblum
Date: 2015-02-02 15:34:12.648249
SUPPORTING DOCS: deleting supporting docs now happens in the backend **OC UPDATE REQUIRED**

M   /trunk/code/test/tests/modules/wizard/activeformrouterSpec.js
M   /trunk/code/app/modules/wizard/models/summary.js
M   /trunk/code/app/modules/wizard/views/controltypes.js

Revision: 10691
Author: mblum
Date: 2015-02-02 15:21:10.851374
WIZARD SUPPORTING DOCUMENTS + EXPORT FORMS: supproting docs are now properly deleted when a page is removed from flowpath, deleted as a grouped question, or replaced with another document. export forms now abides by the bulk upload contract of a map of object names and object Ids.

M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/executer/ExportFormsActionExecuter.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/core/Wizard2Impl.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/executer/FinishAndSubmitPSIActionExecutor.java
A   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/PSIJSONUtil.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard-client/src/main/java/com/tsgrp/opencontent/wizard/core/model/util/Wizard2Constants.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/executer/SaveWizardFormActionExecuter.java
