### ISSUE TITLE
Alfresco Save and Exit - pdf rendition gets changed/removed from all versions

### ISSUE THREAD

**Issue by aviking** [tsgrp/ActiveWizard#140]
When you complete a form in alfresco, a pdf rendition is created and attached to the form as a child to the form with the assocType = cm:rendition. When you edit the form and update it, the pdf for all the versions gets changed. If you save and exit, there is no pdf for any version, and if you finish and submit there is only a pdf rendition for the most current version. There are two gifs. One demonstrates save and exit and one demonstrates the finish and submit. If a version has a rendition it is supposed to keep the rendition. Here's an example of how it should work: If you start and finish a form you should/will have a 0.1 with a pdf rendition. If you edit the form, make a change, and hit save and exit you should have a 0.1 with the same pdf rendition as before and a 0.2 without a pdf rendition. If you edit the form again, make a change, and hit finish, you should have a 0.1 with the original pdf rendition, a 0.2 without a pdf rendition, and a 0.3 with a new pdf rendition.

![alfrescorenditionissue](https://cloud.githubusercontent.com/assets/2895070/5320015/ce82b618-7c73-11e4-8baf-eb94b2052f3d.gif)

![alfrescorenditionissue2](https://cloud.githubusercontent.com/assets/2895070/5320016/d245a4c2-7c73-11e4-96a3-591377549888.gif)

**Comment by mikeblum** [comment]
**OC Update required**

tested on edge and we look good to go. closing...

Revision: 10414
Author: mblum
Date: 2015-01-06 11:41:04.440844
- reverted addRendition code in AlfrescoEmbExtendedContentImpl which resolves this issue: https://github.com/tsgrp/ActiveWizard/issues/140. 

- Adding CAMBRIDGE alfresco wizard env files. 

- Rolling back module-context back from aw:controlled_document to cm:content

- WARNING: if using an alfresco wizard project, clear your solr alfresco model caches

CR dgrumieux

A	/webservices/trunk/SourceCode/OpenContent/projects/tsg/wizardAlfresco/overlay/cambridge/config
A	/webservices/trunk/SourceCode/OpenContent/projects/tsg/wizardAlfresco/build-CAMBRIDGE.properties
M	/webservices/trunk/SourceCode/OpenContent/modules/tsg/4.wizardAlfresco/config/alfresco/module/com.tsgrp.opencontent/model/awModel.xml
M	/webservices/trunk/SourceCode/OpenContent/modules/tsg/2.alfrescoEmb/src/com/tsgrp/opencontent/alfresco/extendedcontent/AlfrescoEmbExtendedContentImpl.java
A	/webservices/trunk/SourceCode/OpenContent/projects/tsg/wizardAlfresco/overlay/cambridge/config/rebel.xml
M	/webservices/trunk/SourceCode/OpenContent/projects/tsg/wizardAlfresco/classes/alfresco/module/com.tsgrp.opencontent/module-context.xml
A	/webservices/trunk/SourceCode/OpenContent/projects/tsg/wizardAlfresco/overlay/cambridge
M	/webservices/trunk/SourceCode/OpenContent/projects/clients/fedex
