### ISSUE TITLE
Edit Form: can edit a non-latest version of a form

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#151]
Steps:

1. Create a form
2. save and exit twice so you have:
  - 0.1
  - 0.2
3. edit form once more and complete the form to get the following versions:
  - 0.1
  - 0.2
  - 0.3

4. select 'view versions' and select one of the previous versions
5. you'll see the edit form action available even though this form is already finished.

we most likely need to add a condition bean that says if a form doesn't have LATEST or CURRENT flags (for dctm) and then if not in the workspaces:spacesstore (for alfresco) then fail.

**Comment by gsteimer** [comment]
This should only be an issue in Documentum.  I believe if you tried this in Alfresco, it would just start editing the latest version.  We should verify this however.

I believe we already have a condition that lets you say that a document is the `CURRENT` version, so this should be pretty easy.

**Comment by gsteimer** [comment]
From talking to @mikeblum, this is an issue on Alfresco since the previous versions have VersionStore IDs vs. SpacesStore IDs.  Perhaps we need an "isInSpacesStore" condition or something like that?

@dgrumieaux - thoughts?

**Comment by dgrumieaux** [comment]
I think the "isInSpacesStore" condition would solve this problem for Page Set Instances as they are currently supported (ie not going past version 1.0)

**Comment by gsteimer** [comment]
We need a generic condition for this.  See here: https://github.com/tsgrp/OpenContent/issues/47

**Comment by benallenallen** [comment]
Commit a fix in OC 13909 that added the "condition-isobjectcurrent-conditionevaluator" condition to the resumeForm action that prevents a user from being able to do this. Tested on edge1 and edge2.

CR George
