### ISSUE TITLE
Firefox: radio buttons don't register with the question model

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#154]
Checkboxes work but radio buttons don't update the backing model to validate the question. Thus we can't complete a form if that question is required. Creating a TS Firefox to capture any browser-specific controls issues.

**Comment by gsteimer** [comment]
@mikeblum - I'm taking off the High Priority label.  The majority of our clients use IE or Chrome.

**Comment by mikeblum** [comment]
Revision: 11476
Author: mblum
Date: 2015-01-09 13:25:32.550219
Wizard on Firefox: fixing https://github.com/tsgrp/ActiveWizard/issues/154 where radio buttons didn't correctly fire a change event. tested chrome, fox, and ie 9.

M	/trunk/code/app/modules/wizard/views/controltypes.js
