### ISSUE TITLE
Workflow Summary Page - UI Cleanup

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#155]
Some things I've noticed:

- [x] In mobile view, the role detail disappears (this is an issue.  The issue label can be removed once this is fixed).
- [x] The Role Name should be more prominent
- [ ] Better distinction is needed between the Top Level rules tripped and the user rules tripped
- [ ] Easier to see what roles are in what priority.  I know it's there now, but I feel like we can make this nicer.  Notice how in the Flex version, there's a clear color distinction and it's really easy to see what role goes it what task.

See the screenshots below for reference

**Normal Workflow Summary Page**
![image](https://cloud.githubusercontent.com/assets/1377228/5724186/9e991ff4-9b0f-11e4-822a-c1b73927f82c.png)

** Workflow Summary Page - Mobile Width**
![image](https://cloud.githubusercontent.com/assets/1377228/5724191/ae1fe7f0-9b0f-11e4-8e4c-cd2ed02f4885.png)

**Workflow Summary Page - Two roles at same priority**
![image](https://cloud.githubusercontent.com/assets/1377228/5724237/f7a1c16e-9b0f-11e4-8fc2-193de170eb43.png)

**Flex Workflow Summary Page**
![image](https://cloud.githubusercontent.com/assets/1377228/5724205/be8899ca-9b0f-11e4-9b55-e9bdf0dacfac.png)

@dgrumieaux @mikeblum - may or may not be a problem for your upcoming client project.

**Comment by mikeblum** [comment]
removed hidden-sm and hidden-xs so now wf shows up on mobile.

**Comment by mikeblum** [comment]
Now shows up in mobile with a few styling tweaks

Revision: 11558
Author: mblum
Date: 2015-01-21 13:19:59.806352
WIZARD WORKFLOW: solved the following issues: hard refreshing a resumed form now loads the form again rather then blanking out. when no workflow rules are tripped we show a message to the user, if no wf rules are tripped we return an empty string to oc to stop a hollow wf definition being generated. lastly refactored our psi attributes to psiName, psdName, and psiType to clear up some name ambiguities. 

M   /trunk/code/app/modules/wizard/activeform.js
M   /trunk/code/app/templates/wizard/psi-header.html
M   /trunk/code/app/modules/wizard/activeformrouter.js
M   /trunk/code/app/modules/wizard/models/pagesetinstance.js
M   /trunk/code/app/modules/wizard/views/workflowsummaryview.js
M   /trunk/code/app/modules/wizard/pagesetinstanceuploadutils.js
M   /trunk/code/app/templates/wizard/workflowsummarypage.html
M   /trunk/code/assets/css/styles/wizard.styl
M   /trunk/code/app/modules/wizard/views/summaryview.js
M   /trunk/code/app/modules/wizard/models/workflow/workflow.js
M   /trunk/code/app/modules/wizard/services/pagesetinstanceprovider.js
M   /trunk/code/app/modules/wizard/views/psiheaderview.js
M   /trunk/code/app/modules/wizard/services/psiutilservice.js

**Comment by gsteimer** [comment]
Latest and greatest:

![image](https://cloud.githubusercontent.com/assets/1377228/7208516/0f59c90a-e507-11e4-90f7-85b96a54420a.png)
