### ISSUE TITLE
Start Approval Route: if no workflow rules are tripped, the user shouldn't be able to start an approval route

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#160]
One edge case in the new workflow implementation is that we always expected a workflow rule to be tripped. We'll need to account for the case of no workflow rules being tripped (see TS WF User Rules for an example of this). In this scenario, we'll want to show a message to the user in the workflow summary page that no workflow rules were tripped and then from a technical standpoint, not create or attach a workflow defintion object in OC. Once this happens, the test scenario is to not trip any WF rules, and see if you can start an approval route. Note: related to #159, you should still be able to start a review route.

**Comment by gsteimer** [comment]
Note that in this case, you _should_ be able to start a Route for Review.  As with #159, delegate and reassign should work as expected.

**Comment by dgrumieaux** [comment]
A test case for this issue is if a user finishes a form with available workflow rules, then edits the form such that no workflow rules are tripped, then finishes the form. The previously valid workflow definition should be either deleted or at least have the relationship removed from the 0.2 version of the form.

**Comment by mikeblum** [comment]
Revision: 11558
Author: mblum
Date: 2015-01-21 13:19:59.806352
WIZARD WORKFLOW: solved the following issues: hard refreshing a resumed form now loads the form again rather then blanking out. when no workflow rules are tripped we show a message to the user, if no wf rules are tripped we return an empty string to oc to stop a hollow wf definition being generated. lastly refactored our psi attributes to psiName, psdName, and psiType to clear up some name ambiguities. 

M   /trunk/code/app/modules/wizard/activeform.js
M   /trunk/code/app/templates/wizard/psi-header.html
M   /trunk/code/app/modules/wizard/activeformrouter.js
M   /trunk/code/app/modules/wizard/models/pagesetinstance.js
M   /trunk/code/app/modules/wizard/views/workflowsummaryview.js
M   /trunk/code/app/modules/wizard/pagesetinstanceuploadutils.js
M   /trunk/code/app/templates/wizard/workflowsummarypage.html
M   /trunk/code/assets/css/styles/wizard.styl
M   /trunk/code/app/modules/wizard/views/summaryview.js
M   /trunk/code/app/modules/wizard/models/workflow/workflow.js
M   /trunk/code/app/modules/wizard/services/pagesetinstanceprovider.js
M   /trunk/code/app/modules/wizard/views/psiheaderview.js
M   /trunk/code/app/modules/wizard/services/psiutilservice.js

*\* OC Update Required **

Revision: 10581
Author: mblum
Date: 2015-01-21 13:09:32.353227
WIZARD WORKFLOW ROUTING: fixes for removing workflow definitions in the following situations: saving a form, canceling a workflow (only removing when canceling an approval route), finishing a form and no wf rules have been tripped.

M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/executer/CancelWizardWorkflowActionExecuter.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/classes/wizard-condition-bean-config.xml
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/executer/SaveWizardFormActionExecuter.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/workflow/Wizard2WorkflowImpl.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/core/Wizard2Impl.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/classes/wizard-action-bean-config.xml
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/workflow/IWizard2Workflow.java
A   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/condition/evaluator/DoesFormHaveWizardWorkflowAttached.java
M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/action/executer/FinishAndSubmitPSIActionExecutor.java
