### ISSUE TITLE
Do not evaluate workflow rules when form is in an approval route

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#167]
Users should be able to edit both forms and workflow documents in an approval route.  Note: #86.

However - if the user is editing a **form** during it's approval route, we should NOT process the workflow rules.  Since the approval workflow is already started, updating the workflow definition would be a bad idea.

Also - remember that if the user edits a form in it's review route, it's perfectly fine to evaluate the workflow rules and generate a new workflow definition.

**Comment by gsteimer** [comment]
@dgrumieaux @mikeblum - this may be an issue for your current client if they can edit forms during the approval route.

@benallenallen - do you know if that's the case?

**Comment by dgrumieaux** [comment]
Fixed in HPI 11753/OC 10870. Tested against Dctm. Pending edge1 test before closing.

**Comment by dgrumieaux** [comment]
Tested with SCR-134 on edge1, passed. Closing.

**Comment by dgrumieaux** [comment]
Note that the resumeform action, by default, does not reevaluate workflow definitions for the Pending Approval state, and that that setting can be overridden via config-project.js's "noWfDefStates" array.
