### ISSUE TITLE
Metadata Rules: saving a form or finishing the form a second time doesn't update metadata rules

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#175]
Currently , questions that set a property on the repo object are only added at create time, not on ensuing versions of the form. We'll need to pass these scenarios:
1. Add a page to the flowpath, answer a question that changes a metadata attribute. Save the form and the metadata attr should have updated.
2. remove a page from the flowpath that modifed a metadata attribute. That metadata attribute should be cleared out.
3. right now metadata only supports non-repeating string attributes - we'd need to enhance the code to handle repeating metadata fields like authors, keywords,, etc

**Comment by gsteimer** [comment]
Closing since #179 handles this issue plus more.
