### ISSUE TITLE
PSA - archiveAll and uploadAll options should not prompt the user

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#176]
When using the `archiveAll` or `uploadAll` options, the user should not be prompted if workflow rules should be archived or upload.  It should just assume that everything is processed.  See below:

**archiveAll**
![image](https://cloud.githubusercontent.com/assets/1377228/6070143/cca6b65c-ad4f-11e4-80db-e905c01f9814.png)

**uploadAll**
![image](https://cloud.githubusercontent.com/assets/1377228/6081474/5c8fccb0-addf-11e4-9565-b1a31961d564.png)

The whole point of the `archiveAll` and `uploadAll` options is that they can be used for clients who have many form templates.  It would be really annoying to have to type 'y' and [enter] for every form.  Maybe get two bobble ducks a-la Homer Simpson as a workaround?

I'm marking this as an issue since the 4.0 PSA tool had this functionality and it looks to be lost in the 5.0 version.

**Comment by mikeblum** [comment]
Fixed this a while ago:

r12256 | mblum | 2015-05-19 10:37:58 -0500 (Tue, 19 May 2015) | 1 line

Bulk Archive and Bulk Upload: script no longer asks for user input to archive or upload bulk forms for replacing a form or workflow rules. Fixed infinite loop of trying to upload a failed form as well.
