### ISSUE TITLE
Date fields cannot be optional

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#178]
See the screenshot below.  In this form, the Set Approved Date question is optional, but the page is not validating appropriately:

![image](https://cloud.githubusercontent.com/assets/1377228/6087995/855a598e-ae17-11e4-8c7c-b9a4570dda2d.png)

@dgrumieaux @mikeblum - not sure if this is an issue for your current client.

**Comment by mikeblum** [comment]
Revision: 11987
Author: mblum
Date: 2015-04-02 15:22:23.482538
WIZARD - optional dateboxes are allowed now. Tests to confirm date formatting issues. CR dgrumieaux Closing Active Wizard issue #178

M   /trunk/code/app/modules/wizard/services/formatservice.js
M   /trunk/code/app/modules/wizard/services/validationservice.js
M   /trunk/code/test/tests/modules/wizard/services/formatserviceSpec.js
