### ISSUE TITLE
Metadata Rules - Support in HTML5 Active Form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#179]
Metadata rules, which work on the client branch that started the HTML5 module, no longer work in trunk.  

The scenarios that should be tested are encapsulated in the `TS Metadata Rules` form.  The psa for Documentum is in svn.  If, while working on this bug, you can come up with a repo-agnostic version that touches all of the test cases below, that would be awesome.  In it's current state, I don't think all the attributes set in the form are available on `aw:psi` in Alfresco.

While working on this, we need to ensure the following cases pass:
- [x] Set property from:
  - [x] textbox
  - [x] textarea
  - [x] select box
  - [x] radio
  - [x] Date
  - [x] checkbox
  - [x] Multi-text
  - [x] Multi-select toss across
- [x] Set property based on (depending on configuration):
  - [x] answer value
  - [x] answer display text
  - [x] answer justification
- [x] Set Single valued attributes
- [x] Set repeating valued attributes
- Set attributes upon: 
  - [x] Finish of a new PSI
  - [x] Finish of an existing PSI (you edited an existing PSI)
  - [x] Save & Exit
- [x] Set properties on an optional page
- [x] Set properties on an optional question (ex: value is removed, property should clear)
- [x] If said optional page above is removed from the flowpath upon editing the page, any attributes are cleared out.

Once we can set single valued String fields from textbox and selectbox, the issue tag can be removed.  Anything above that is an enhancement.

Note that, in the current state of trunk, nothing actually bombs out.  it just sets the attribute to 'Not Found' in place of the answer from the form.

See also #175 - I'm closing it since this issue encompasses everything raised there and more.

**Comment by gsteimer** [comment]
Just tried this out on Edge1 with a really simple example:
- TS Metadata Rules (modified for really simple scenario)
- One Page, one textbox
- Set the `subject` attributes

When trying to finish the form, it fails:

![image](https://cloud.githubusercontent.com/assets/1377228/6756654/429b631a-cef9-11e4-88b2-05b144ee0cd3.png)

The OC error is:

```
2015-03-20 12:00:25,294 12082084    TP-Processor7   ERROR   RESTService Error creating pdf rendition of wizard form!
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error creating pdf rendition of wizard form!
    at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.jsonToPdf(FinishAndSubmitPSIActionExecutor.java:306)
    at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:60)
    at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)
    at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:303)
    at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

@mikeblum @dgrumieaux  - I thought we had this working for our current client?  @ladams13 needs something similar for another client implementation...

**Comment by gsteimer** [comment]
If I try to save and exit vs. finish, I get these errors:

![image](https://cloud.githubusercontent.com/assets/1377228/6756700/a9a7d46c-cef9-11e4-9f8d-252dc8f5d130.png)

```
2015-03-20 12:04:37,263 12334053    TP-Processor3   ERROR   RESTService Failed to retrieve questions and answers from the page set instance
com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to retrieve questions and answers from the page set instance
    at com.tsgrp.opencontent.wizard.PSIJSONUtil.getSupportingDocsFromPageSetInstance(PSIJSONUtil.java:200)
    at com.tsgrp.opencontent.wizard.PSIJSONUtil.resolveSupportingDocRelations(PSIJSONUtil.java:39)
    at com.tsgrp.opencontent.wizard.action.executer.SaveWizardFormActionExecuter.executeImpl(SaveWizardFormActionExecuter.java:54)
    at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)

...

Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: Error parsing JSON
    at com.tsgrp.opencontent.wizard.PSIJSONUtil.pageIsInFlowpath(PSIJSONUtil.java:241)
    at com.tsgrp.opencontent.wizard.PSIJSONUtil.getSupportingDocsFromPageSetInstance(PSIJSONUtil.java:160)
    ... 33 more
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: flowpath malformed! node not found on flowpath: pg1
    at com.tsgrp.opencontent.wizard.PSIJSONUtil.pageIsInFlowpath(PSIJSONUtil.java:236)
    ... 34 more
```

**Comment by dgrumieaux** [comment]
My guess here is that the metadata rules are not necessarily misbehaving - this appears to be an issue with the TS Metadata Rules Page Set, or an issue of the new HTML5 interface not interpreting the TS Metadata Rules Page Set correctly.

**Comment by gsteimer** [comment]
@dgrumieaux - hmm... yeah, I think this is a separate issue.  I'll create a new issue for this one.

**Comment by gsteimer** [comment]
@dgrumieaux @mikeblum - Ok, after fixing the orphaned pages issue, I'm seeing the same thing that @ladams13 is seeing.  It's also the same thing I was seeing before Mike fixed the issue for our current client.  Basically, the attribute gets set with a 'Not Found' value. 

Edge1 with the `TS Simple Metadata Rules` page set has this scenario configured:

**AW Admin**
![image](https://cloud.githubusercontent.com/assets/1377228/6759079/4fdc1aee-cf0b-11e4-877f-e19f84e97ef9.png)

**Form PDF**
![image](https://cloud.githubusercontent.com/assets/1377228/6759066/2a1781b8-cf0b-11e4-8d08-0302408b72d3.png)

**Dctm Attr**
![image](https://cloud.githubusercontent.com/assets/1377228/6759068/31d4e6fc-cf0b-11e4-994d-8878ef88ea7c.png)

**Comment by mikeblum** [comment]
Revision: 11948
Author: mblum
Date: 2015-03-27 09:30:25.279413
METADATA RULES: non-required questions can now be blanked out and removed from the metadadta map sent to OC.

M   /trunk/code/test/tests/modules/wizard/wizard/metadataSpec.js
M   /trunk/code/app/modules/wizard/models/metadata.js

**Comment by mikeblum** [comment]
Support for repeating attributes and non-required/optional pages is still outstanding

**Comment by gsteimer** [comment]
Updated the checklist in the OP.  The following cases do not work with the latest TS Simple Metadata Rules form template:
- Answer justification - seems broken overall.  When I click on an answer that requires justification, no justification area pops up - more investigation (and probably an issue) soon...
- Optional questions  - if you enter a value for an optional question, the value appears properly.  However, if you go back in and clear out the answer, the corresponding answer is not cleared.  See below:

**Form**
![image](https://cloud.githubusercontent.com/assets/1377228/6922618/11c0ae66-d792-11e4-9558-99af31d6ce62.png)

**Properties after save**
![image](https://cloud.githubusercontent.com/assets/1377228/6922622/23434086-d792-11e4-94f9-e1d8f19635bf.png)

@mikeblum

**Comment by gsteimer** [comment]
Update - justifications do work properly for radio button questions.  See the TS Answer Justifications page set for an example.

**Comment by mikeblum** [comment]
Revision: 11959
Author: mblum
Date: 2015-03-31 10:55:23.685663
METADATA: rolling back check for empty metadata answers as that broke blanking an existing value. Will need to revisit for repeating vlaues.

M   /trunk/code/app/modules/wizard/models/metadata.js

**Comment by mikeblum** [comment]
What is the precedence of configured metadata rules on a single question:
1. justification
2. display text
   followed by
3. value

**Comment by mikeblum** [comment]
*\* OC Update required **

Revision: 11991
Author: mblum
Date: 2015-04-02 16:52:29.107538
METADATA: solved all the scenarios on gh for now. unit tests and some wizard patch fixes for justifications (issue still outstanding). CR dgrumieaux

M   /trunk/code/app/modules/wizard/formfields/aspects.js
M   /trunk/code/test/tests/modules/wizard/wizard/metadataSpec.js
M   /trunk/code/app/templates/common/typeahead/typeahead.html
M   /trunk/code/test/tests/modules/wizard/wizard/fieldSpec.js
M   /trunk/code/app/modules/wizard/models/pagesetinstance.js
M   /trunk/code/app/modules/wizard/views/controltypes.js
M   /trunk/code/app/modules/wizard/models/metadata.js
M   /trunk/code/assets/css/styles/wizard.styl

Revision: 11291
Author: mblum
Date: 2015-04-02 16:54:15.935663
METADATA: changes to the getMetadata code to support repeating values and dates as well as single string values.

M   /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/core/Wizard2Impl.java

**Comment by gsteimer** [comment]
@mikeblum - precedence should be based on the order of the actions in AW admin.  I believe in the old ActiveForm, last won.  The typical case you'd configure more than one is with answer justification.  So you'd configure answer value or display text first, and then answer justification as the second action.  So that way, answer justification would only get saved to the attribute if the user actually entered a justification value.

**Comment by mikeblum** [comment]
Revision: 11992
Author: mblum
Date: 2015-04-03 11:07:18.513788
METADATA 2.0: added functionality for precedence of metadata rules where the last one wins. Tests confirm (TS Simple Metadadta Rules). CR dgrumieaux

M   /trunk/code/test/tests/modules/wizard/wizard/metadataSpec.js
M   /trunk/code/app/modules/wizard/models/metadata.js
