### ISSUE TITLE
Queries must be able to work on checkbox and radio question types

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#181]
Currently, queries can only be applied to the Select Box and Multi-Select Toss Across question types.  Many clients have radio button and checkbox questions that are driven by a query as well.

Currently, it looks like the query runs, but the display is blank.

When implementing this fix, we should probably create a new `TS Answer Query.psa` sample archive.

**Comment by mikeblum** [comment]
Revision: 12011
Author: mblum
Date: 2015-04-06 15:02:03.948430
Wizard: queryable radio buttons and checkboxes using TS Answer Query. CR dgrumieaux. *\* OC update required *\* As of this commit justifications only work wiith static answers.

M   /trunk/code/app/modules/wizard/models/question.js
M   /trunk/code/app/modules/wizard/models/summary.js
M   /trunk/code/app/modules/wizard/views/controltypes.js
M   /trunk/code/test/tests/modules/wizard/wizard/questionSpec.js
M   /trunk/code/app/templates/formfields/checkboxescontrol.html
M   /trunk/code/app/templates/formfields/radiocontrol.html

**Comment by gsteimer** [comment]
This is still not working on edge with TS Answer Query:

![image](https://cloud.githubusercontent.com/assets/1377228/7302035/22bba690-e9ac-11e4-9d90-ece6417a5618.png)

@mikeblum - I'm in the process of revamping the TS Answer Query form to have better test cases.  I'll let you know when it's ready.

**Comment by mikeblum** [comment]
Those pass-through query questions might be broken.  We have an outstanding
issue with those.

**Comment by gsteimer** [comment]
The queries seem to be working.  I tried this again, and it looks like they do work on radio / checkbox - just not the first time the form loads:

![aw-query-radio-and-checkbox](https://cloud.githubusercontent.com/assets/1377228/7304293/0c469aa4-e9bc-11e4-8bf1-6c8b0b417538.gif)

**Comment by mikeblum** [comment]
Since its using passthrough quesries, I think this may have to do with #204

**Comment by mikeblum** [comment]
r12646 | mblum | 2015-07-01 15:40:57 -0500 (Wed, 01 Jul 2015) | 1 line

WIZARD TS CASCADING QUERIES: overhaul of rules and placeholders in the wizard to support complex cascading query situations (see TS Cascading Queries). Closing #181, #204, #207, #206, #236, #238
