### ISSUE TITLE
Save & Exit does not work when form has not been completed

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#184]
I can't pin down the exact scenario for this, but it seems like save and exit throws an error, but the save actually works.  From what I can tell, if you finish the form and then edit it again and save/exit, it works fine.  But, if you try to save and exit before finishing, you get this:

![save-and-exit](https://cloud.githubusercontent.com/assets/1377228/6216744/561b4bde-b5d2-11e4-98eb-e5ada31ca510.gif)

When the error occurs, my location bar looks like this:

![image](https://cloud.githubusercontent.com/assets/1377228/6216761/70df800c-b5d2-11e4-91c0-22be615d2063.png)

@dgrumieaux @benallenallen @mikeblum - Marking this as high priority since our current client will need this to work.

**Comment by mikeblum** [comment]
Issue was unanswered repeating questions didn't have a value attribute and the code that parsed for supporting docs would fail. The reason this didn't affect form gerneation was that this code runs after a form has already been created in the repo

**Comment by mikeblum** [comment]
Revision: 10916
Author: mblum
Date: Thursday, February 19, 2015 10:44:13 AM
Message:

## SAVE & EXIT WIZARD FROM: fix for https://github.com/tsgrp/ActiveWizard/issues/184. issue was unanswered questions not having a value attribute to grep on. falls back to an empty string.

Modified : /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/PSIJSONUtil.java
