### ISSUE TITLE
Passthrough queries should process column names properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#185]
Passthrough queries should process columns based on the assumption that any column name in the answer value or display text will be replaced when the query is run.

With how it is now, it's impossible to have one query that does something like this:

``` SQL
select user_login_name, user_name, user_address from dm_user where user_name = USER;
```

And then have two question setup like this:
- Question 1
  - Value: user_login_name
  - Display: user_name
- Question 2
  - Value: user_address
  - Display: user_address

In the above scenario, Question 1 works fine, but question 2 displays the user_login_name rather than the user_address.

From talking to @mikeblum, it sounds like the code assumes that if there's two columns selected, the first is the value and the second is the display.

**Comment by mikeblum** [comment]
Revision: 11810
Author: mblum
Date: 2015-02-27 12:50:33.330058
WIZARD QUERY SERVICE: fixed query parsing to not rely on the column order and instead use the question's configured value and displayValue in the AW Admin. CR dgrumieaux

M   /trunk/code/app/modules/wizard/models/question.js
M   /trunk/code/app/modules/wizard/services/pagesetinstanceprovider.js
M   /trunk/code/app/modules/wizard/formfields/aspects.js
M   /trunk/code/test/tests/modules/wizard/wizard/questionSpec.js
M   /trunk/code/test/tests/modules/wizard/services/queryserviceSpec.js
M   /trunk/code/app/modules/wizard/services/queryservice.js

**Comment by gsteimer** [comment]
@mikeblum - can you check with @ladams13 on this one?  She has a pretty recent OC (from this week), but she's seeing the exact same issue that I had in my original post.

Re-opening this until we can confirm that it's no longer an issue...

**Comment by mikeblum** [comment]
Using the following query:

```
select user_login_name, user_name, user_address from dm_user where user_name = USER;
```

Can't re-produce on trunk. Closing.

**Comment by gsteimer** [comment]
This is still not working properly per how the Flex module worked.  It seems to work properly when you use _one_ value in the display, but not _two_.  See the `TS Passthrough Query` page set on edge1.

**Admin - note the use of more than one attr in the display**
![image](https://cloud.githubusercontent.com/assets/1377228/7892267/bc272a24-0618-11e5-88f3-4bc12983af1e.png)

**Form - note that only the user name displays**
![image](https://cloud.githubusercontent.com/assets/1377228/7892288/d7c016ba-0618-11e5-81e2-0c0c97763279.png)

**Comment by gsteimer** [comment]
Lowering the priority of this, since the base scenario that's working is the one we use the most.

**Comment by gsteimer** [comment]
Actually, this is a dupe of #207
