### ISSUE TITLE
Duplicate forms are created when hitting the browser back button

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/ActiveWizard#186]
In the latest codebase, if a user creates a form, then navigates back to the "submit" URL, a new form is automatically created from the same data as the previous form. We should make sure to either remove the "submit" URL from Backbone history (never put it on the history in the first place, most likely) or clear out the form's data from memory.

**Comment by grahamsinger** [comment]
Fixed. Awaiting CR

**Comment by grahamsinger** [comment]
Fixed with rev.12695

Temporarily stopped Backbone history so that the submit URL doesn't get added to the history.  It seems as though the `{replace : true}` option wasn't enough to accomplish this due to us having multiple routers in memory.
