### ISSUE TITLE
When many roles are tripped, WF Summary page doesn't start scrolled to top

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#187]
See the screencam below.  Really odd, but when I have about 5 roles tripped, the WF Summary page seems to display initially scrolled about halfway down.

@dgrumieaux @mikeblum @benallenallen - not sure if this is an issue for our current client.  Have you guys noticed this with their form(s)?

![wf-summary-middle](https://cloud.githubusercontent.com/assets/1377228/6237983/faa9ca0a-b6bc-11e4-8692-00227119570a.gif)

**Comment by ghost** [comment]
Added window.scrollTo(0,0) on both summary pages to make sure theyre reset when navigated to. 
CR- Dan G.
HPI - 11830
