### ISSUE TITLE
Wizard Inbox form link does not link to CURRENT form

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/ActiveWizard#188]
When a wizard inbox link is clicked, it should navigate to the CURRENT form version. However, this does not currently happen - instead, we may be taken to an older version of the form. To reproduce this issue, create a form, route it for review, then edit the form once to create a 0.2 version. Then go to the review task owner and click the form link on the dashboard, and check to see the version of the form loaded into the stage.

**Comment by dgrumieaux** [comment]
Marking as high priority due to confusing user experience this could provide to a client.

**Comment by gsteimer** [comment]
Interesting - it makes sense that this is behaving this way, but I thought I could get around the issue by doing this:
1. Click on the inbox link.  As expected it goes to the old version, say `0.2`.
2. Click view versions, and load the `0.3, CURRENT` version into the stage.
3. Here - I'd expect to see the complete and delegate task actions, but I don't:

![image](https://cloud.githubusercontent.com/assets/1377228/6267422/75041a60-b809-11e4-8400-d7df7e65c355.png)

Even more odd, if I do this:
1. Click on the email link, loads the 0.3 version in the stage with the actions as expected
2. Click view versions, and load the `0.3, CURRENT` version into the stage.
3. Here - I'd expect to _not_ see the complete and delegate task actions as above, _but I do_

**Comment by dgrumieaux** [comment]
The reason why that workaround does not work is because the containerID is
not updated by the view versions link.

**Comment by gsteimer** [comment]
Ah, yeah - that makes sense.

**Comment by dgrumieaux** [comment]
Is is a problem that the actions on the left do not change if we change the form version we are looking at? For instance, if the user is on the 0.2 CURRENT form, then we switch the version to the 0.1 form, we still see the Wizard Actions for the 0.2 CURRENT form.

**Comment by dgrumieaux** [comment]
HPI rev 11795 fixes the issue such that the awinbox link goes to the CURRENT version of the form.

WIZARD INBOX: Force form to go to wizard trac and to always get the CURRENT form in order to keep users from being confused about not seeing their wizard task.

Fixes AW/issues/188.

**Comment by gsteimer** [comment]
@dgrumieaux - I don't think that's an issue.  Users rarely view a form's prior versions in real world scenarios, so I think it's fine that we're always showing the actions for the CURRENT form.  

@benallenallen - do you disagree?

**Comment by benallenallen** [comment]
This seems fine that the actions always are performed on the "CURRENT" version of the form... what actions would they even want to do on the previous ones? The only one I can think of is "view annotations" but they already have a link to do that in the "View Versions" action, so that seems fine to me.

**Comment by dgrumieaux** [comment]
Based on the comments, I think we're safe to close this issue.
