### ISSUE TITLE
Workflow rules are not evaluating properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#190]
See the screencam below.  It looks like the workflow summary page is not displaying the correct users for the Initial QA role. 

![wf-rules-eval](https://cloud.githubusercontent.com/assets/1377228/6380123/f1af9ba0-bcfc-11e4-9b38-7cf38de3d993.gif)

I see two issues:
- [ ] The workflow summary page is displaying the wrong user for the IQA role
- [ ] The reason for the approver being selected is wrong (see below)

In the screenshot below, it looks like the high level rule is being used to determine the approver.  The IQA role should trip with:
- High level rule - Priority of Change is not Low
- User level rule - Priority of Change is Medium
- User is Max

![image](https://cloud.githubusercontent.com/assets/1377228/6380164/3ad20250-bcfd-11e4-89ac-c5e2d01c39a6.png)

@mikeblum @dgrumieaux - Not sure if this is a problem for our current client's form, but we'll definitely need this for the HPI 2.3 release since we primarily demo with the Simple CR form.

**Comment by mikeblum** [comment]
This appears to just be a front end issue

**Comment by mikeblum** [comment]
Revision: 11808
Author: mblum
Date: 2015-02-26 16:14:03.267558
WORKFLOW RULE SUMMARY PAGE: simplifying generation of the tripped workflow rules to use the exact same json that is sent to OC. Closing https://github.com/tsgrp/ActiveWizard/issues/190 CR dgrumieaux

M   /trunk/code/app/modules/wizard/models/workflow/workflowruleevaluator.js
M   /trunk/code/app/templates/wizard/workflowsummarypage.html
M   /trunk/code/app/modules/wizard/models/workflow/workflow.js
