### ISSUE TITLE
Exiting an existing form shows error message, but actually works

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#191]
See the screencam below.  Note that the cancel checkout actually does happen.

![cancel-checkout](https://cloud.githubusercontent.com/assets/1377228/6380201/8de4f862-bcfd-11e4-8338-6e0bd3552773.gif)

@dgrumieaux @mikeblum - I'm assuming this will be needed for our current client.  This will definitely be needed for the HPI 2.3 release.

**Comment by tconnellytsg** [comment]
Turns out this issue was being caused because we weren't properly checking out the document on the initial navigation to the form, and so when OC went to cancel the checkout it actually did throw an error because there was no lock owner.

Fixed and waiting on CR before commit.

**Comment by tconnellytsg** [comment]
Fixed in hpi revision #11806
