### ISSUE TITLE
Textarea - support hard breaks

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#192]
The text area control should support hard breaks properly:

Edit Control:
![image](https://cloud.githubusercontent.com/assets/1377228/6396440/1e777d40-bda4-11e4-940d-b0e916e77d91.png)

Summary Page:
![image](https://cloud.githubusercontent.com/assets/1377228/6396451/2a51f668-bda4-11e4-96d4-f65995be863d.png)

PDF:
![image](https://cloud.githubusercontent.com/assets/1377228/6396465/34aafa56-bda4-11e4-81c6-1ad73525acac.png)

The old wizard supported this, but perhaps we go the route of only supporting this when we implement the WYSIWYG control?  See: #102

**Comment by mikeblum** [comment]
WYSWIG implemented. Can we close this?

**Comment by gsteimer** [comment]
Just tested this with WYSIWYGs and it works.  I'm fine with closing this.
