### ISSUE TITLE
MultiTextInput Control: values wrapped in "double quotes"

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#193]
In both the summary page aand resulting pdf rendition, the multi text input control wraps each value in double quotes:

![selection_001](https://cloud.githubusercontent.com/assets/3905463/6396628/218bcfee-bda5-11e4-8776-7668ca54e48f.png)

First place to look would be in Controltypes.js and see how we process the values coming in.

**Comment by tconnellytsg** [comment]
Fixed in OC Revision #10973
