### ISSUE TITLE
Workflow Summary page - should use question display vs. question short label

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#194]
See the screenshot below.  The Workflow Summary page should be displaying the question display text, not the question short label.

![image](https://cloud.githubusercontent.com/assets/1377228/6419766/c9de6c7a-be85-11e4-94e8-d07291f469a7.png)

![image](https://cloud.githubusercontent.com/assets/1377228/6419755/b5f962aa-be85-11e4-9cea-178ec57789eb.png)

If the question label and display are the same, then obviously this issue is masked.  The above screenshots were taken with the TS Group Based Workflow form template on edge1.

**Comment by mikeblum** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/3905463/6421043/0c19cf98-be91-11e4-8b52-4eedca028532.png)

**Comment by mikeblum** [comment]
Revision: 11814
Author: mblum
Date: 2015-02-27 14:42:16.423808
Wizard Workflow summary page: showing question label rather then the short label: https://github.com/tsgrp/ActiveWizard/issues/194

M   /trunk/code/app/modules/wizard/models/workflow/workflowrule.js
M   /trunk/code/app/modules/wizard/models/workflow/workflow.js
M   /trunk/code/test/tests/modules/wizard/wizard/workflow/workflowruleSpec.js
