### ISSUE TITLE
Radio Buttons: summary page and pdf rendition should show the display value

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#195]
If a radio button has different values vs display values, the HTML5 wizard shows the value incorrectly.

![selection_003](https://cloud.githubusercontent.com/assets/3905463/6452968/ffd7882c-c0fe-11e4-8681-da6219e90bf5.png)

**Comment by mikeblum** [comment]
@tconnellytsg pdf generation code?

**Comment by tconnellytsg** [comment]
We looked at this and it looks like the display value and the value being passed in were the exact same. which would mean that displayvalue isn't properlly being set at some point.

This would also explain why it appears the same in summary view as well.

**Comment by ghost** [comment]
Fixed this by correctly setting and using the displayValue.
HPI REV - 11819
