### ISSUE TITLE
Set Properties Action - Not All Properties Available

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#198]
See the screenshot below (from edge2):

![image](https://cloud.githubusercontent.com/assets/1377228/6692463/c178bd1a-cc9a-11e4-9db4-0f89bfb76f87.png)

I'm guessing this is only showing non-inherited attributes in the dropdown.  We should display all attributes.

**Comment by gsteimer** [comment]
Looking at this again - I'm not sure what the dropdown is showing.  Object Name is inherited....

**Comment by benallenallen** [comment]
Potentially only an Alfresco issue?

**Comment by mikeblum** [comment]
Revision: 7616
Author: mblum
Date: 2015-03-31 15:17:12.920038
OTC Attributes - ALFRESCO: alfresco's inheirited properties come from allProperties not just getProperties. Tested metadata rule on Alfresco and DCTM.

M   /src/trunk/modules/core/WEB-INF/src/com/tsgrp/wizard/tags/GetUpdateablePropertiesTag.java
