### ISSUE TITLE
Answer Justification Issues

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#200]
It appears that answer justifications currently are only supported for radio and checkbox answer types.  The following items from TS Answer Justification do not work.

**Issues (see screencam below)**
- [x] Answer justification text is not appearing on rendered PDF correctly for radio button.  Works properly for checkbox
- [x] When coming back into a form that has justifications rendered, the justification boxes do not show up
- [x] When changing an answer, justification should not be cleared out.  If we need to clear out justification for radio answer changes, that's probably fine.  But we definitely should not clear out checkbox answer justification if a different answer is selected (but the justified answer is not unchecked - see below.

**Enhancements (These can be upon client request)**
- [x] Answer justifications from selectbox (no query)
- [x] Answer justifications from selectbox (with query)
- [x] Answer justifications from multi select (was never supported in AW 3.x or 4.x)

![answer-justifications-issues](https://cloud.githubusercontent.com/assets/1377228/6923615/640c2fa0-d798-11e4-8060-3b51c3d828a7.gif)

**Comment by mikeblum** [comment]
as of Revision: 12011, justifications are noticeably broken and only work with static answers.

**Comment by gsteimer** [comment]
Trying this again with `TS Metadata Rules` - justifications are NOT showing up properly with Checkboxes.

**Comment by mikeblum** [comment]
Revision: 12079
Author: mblum
Date: 2015-04-16 12:51:43.839055
ANSWER JUSTIFICATIONS: support for radio buttons, checkboxes, and typeahead. *\* OC Update required **

M   /trunk/code/app/modules/wizard/models/summary.js
M   /trunk/code/app/modules/wizard/views/abstractcontrol.js
M   /trunk/code/app/modules/wizard/views/controltypes.js
M   /trunk/code/app/templates/formfields/justification.html
M   /trunk/code/test/tests/modules/wizard/wizard/questionSpec.js
M   /trunk/code/assets/css/styles/wizard.styl
A   /trunk/code/test/tests/modules/wizard/wizard/answerjustificationsSpec.js (Copied from  12070)
M   /trunk/code/app/modules/wizard/models/question.js
M   /trunk/code/app/modules/wizard/formfields/aspects.js
M   /trunk/code/app/templates/formfields/selecttypeahead.html
M   /trunk/code/app
M   /trunk/code
M   /trunk/code/test/tests
M   /trunk/code/app/modules/wizard/services/validationservice.js

**Comment by gsteimer** [comment]
Justifications are still not displaying properly on the PDF rendition.  See below:

![image](https://cloud.githubusercontent.com/assets/1377228/7278444/279ecdd0-e8db-11e4-94f4-0a643a3067a3.png)

![image](https://cloud.githubusercontent.com/assets/1377228/7278455/36c5645e-e8db-11e4-8d70-0e4dc74a909b.png)

It looks like only checkbox answers properly display justifications in the PDF.

**Comment by mikeblum** [comment]
@dhartman, @gsteimer - i don't think the changes to the psi -> pdf endition
changes have gone into trunk yet.

**Comment by gsteimer** [comment]
@mikeblum - no problem.  Everything else with Justifications looks good, so once the PDF rendition updates in in trunk, I think we can close this issue.

**Comment by dhartman25** [comment]
@gsteimer @mikeblum the PDF rendition updates are in trunk

**Comment by gsteimer** [comment]
Tested on edge, seems to be working now
