### ISSUE TITLE
Get Page Sets: returning the wrong active version

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#201]
Currently if the active page set definition isn't the LATEST version, the getPageSets endpoint returns the correct active version label but the wrong object id.

here's the wrong response from getPageSets:

``` javascript
{
    "instanceType": "ts_metadata_rules",
    "activeVersionLabel": "1.16",
    "objectId": "0900000280036671",
    "outputType": "XHTML",
    "pageSetName": "TS Simple Metadata Rules",
    "publishedComment": "making date box required to check validation changes",
    "workflowActive": false,
    "version": null
}
```

and dqMan shows that the correct version label is 1.16 bu the objectId is wrong:

![selection_010](https://cloud.githubusercontent.com/assets/3905463/6968181/4ebd5780-d92a-11e4-886b-2e78bf21c38d.png)

The issue appears to be in the query that OC is executing to get the active page sets in Wizard2Impl:getPageSets

**Comment by gsteimer** [comment]
@mikeblum - is anyone actively working on this now?  If not, then this is not a high priority issue.

**Comment by mikeblum** [comment]
In Alfresco, forms set to None still show up in the getPageSets endpoint:

activeVersionLabel: ""
instanceType: "aw_psi"
objectId: "workspace://SpacesStore/97d2606b-5f3c-4079-b5a9-087453c4464f"
outputType: "XHTML"
pageSetName: "TS Email Rules"
publishedComment: "init commit"
version: null
workflowActive: false]

(not reproducible in dctm)

**Comment by mikeblum** [comment]
Revision: 12006
Author: mblum
Date: 2015-04-06 11:29:26.010930
Wizard: starting a new form now gets the ACTIVE version of the page set definition rather then the LATEST version. Tested on alfresco and dctm. Closing https://github.com/tsgrp/ActiveWizard/issues/201

M   /trunk/code/app/modules/wizard/activeformrouter.js
