### ISSUE TITLE
Cascading queries that are tied to query columns do not display properly when triggered a second time

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#204]
Using TS Datasource Query, passing in a user name and getting the correct email address works so long as the user_address is not set to the default option. Going forward, we'll need to keep track of a question's intended column from a query like this: 

```
select user_login_name, user_address from dm_user where user_login_name = '${user_login_name}';
```

**Comment by gsteimer** [comment]
In the old Active Form, we never destroyed the admin's "query answer" - it was never shown to the user, but was used if the query had to be rerun (as in the cascading query case).  I think we need to do something similar here.

**Comment by mikeblum** [comment]
r12646 | mblum | 2015-07-01 15:40:57 -0500 (Wed, 01 Jul 2015) | 1 line

WIZARD TS CASCADING QUERIES: overhaul of rules and placeholders in the wizard to support complex cascading query situations (see TS Cascading Queries). Closing #181, #204, #207, #206, #236, #238

**Comment by gsteimer** [comment]
This still does not work on edge1 `TS Cascading Query`.  Upon editing an existing form, none of the cascading queries work.  This includes questions I've successfully completed in version 0.1 as well as pages I didn't visit the first time through.

However, if I do a hard refresh while in the form, the queries start working again.

![edit-cq-form](https://cloud.githubusercontent.com/assets/1377228/8526943/67827f8a-23cf-11e5-8acb-4c6f33abef83.gif)

**Comment by grahamsinger** [comment]
Addressed with rev.12711

After discussing with @mikeblum this is an OK temporary workaround solution for this and #243 since these errors are quite obvious and annoying.

A fix to strive for would be one that can properly clean and re-do the views and listeners without having to reload the page on subsequent visits to a form.

@gsteimer im not sure if you want to close this and open a new ticket with the above enhancement or keep this and #243 open.

**Comment by gsteimer** [comment]
@grahamsinger - lets close these to keep things organized better.  Create the new enhancement with a 2.4 milestone.  I think it's worth it to pursue the better solution for a better user experience.
