### ISSUE TITLE
Queries in Wizard Forms are failing

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#205]
It appears something has changed in the Wizard Form interface to be improperly sending the executeWizardQuery call to OC. We get back the following error:

```
Required String parameter 'queryName' is not present
```

Replicated in local wizard_d67, edge1, and edge2. Did this start before the 2.3 tag? @gsteimer

**Comment by gsteimer** [comment]
@mikeblum - Queries are working fine on release1/2, so I'd say this was introduced after the 2.3 tag.

**Comment by gsteimer** [comment]
@mikeblum - it looks like the TS Cascading Query form on edge1 is failing.  I'm guessing it's related to this?  I'm just wondering b/c I thought you said you fixed this issue... I'm guessing it's not committed yet?

**Comment by mikeblum** [comment]
I'm using TS Answer Query now. TS Cascading Query hasn't been transformed into JSON from the aw admin it looks like.

**Comment by mikeblum** [comment]
Revision: 12096
Author: mblum
Date: 2015-04-20 11:40:00.384046
WIZARD QUERIES: something changed with the .call context in question.js. Actually referencing the context object directly appears to have fixed the issue.

M   /trunk/code/app/modules/wizard/models/question.js
