### ISSUE TITLE
TS Cascading Query - Does not work at all

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#206]
We need to get TS Cascading Query working on edge.

@mikeblum - I know you mentioned that this form template wasn't upgraded for HTML5, but I went in and republished it.

**Comment by mikeblum** [comment]
Issues List:
- [x] Cascading typeaheads - substitutions should be a map of String -> String not String -> object
- [x] Generated/Dynamic control based on a query/substitution - rendering issues where a question (radio buttons, checkboxes) is dependent on another question. Check change: events.
- [x] Blank out a question's answer if its dependencies changed (See Division -> Site -> Functional configuration)

**Comment by mikeblum** [comment]
r12646 | mblum | 2015-07-01 15:40:57 -0500 (Wed, 01 Jul 2015) | 1 line

WIZARD TS CASCADING QUERIES: overhaul of rules and placeholders in the wizard to support complex cascading query situations (see TS Cascading Queries). Closing #181, #204, #207, #206, #236, #238

**Comment by gsteimer** [comment]
Re-opening this.  TS Cascading Query is broken again on edge1.  The server 500's on the first page with this:

```
2016-04-15 10:59:42,946    38765407    TP-Processor7    ERROR    RESTService    java.util.LinkedHashMap cannot be cast to java.lang.String
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
    at com.tsgrp.opencontent.wizard.core.Wizard2Impl.executeAWQueryAction(Wizard2Impl.java:1045)
    at com.tsgrp.opencontent.wizard.core.RESTWizard2.executeWizardQuery(RESTWizard2.java:155)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by mikeblum** [comment]
r14216 | mblum | 2016-04-18 15:16:44 -0500 (Mon, 18 Apr 2016) | 1 line
Changed paths:
   M /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/core/Wizard2Impl.java

don't try to stringify HashMap parameters for Passthrough queries - TS Cascading Queries back to normal. Closing https://github.com/tsgrp/ActiveWizard/issues/291
