### ISSUE TITLE
Text Fields - delete and backspace keys jump cursor to the end

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#209]
See the screencam below.  If you use the backspace or delete keys in a textarea, the cursor jumps to the end of the textarea:

![textarea-cursor-jump](https://cloud.githubusercontent.com/assets/1377228/7400777/e9eb8500-ee84-11e4-9b98-9ce4419edc09.gif)

Workarounds:
1. Only delete from the end
2. Highlight what you want to delete, then hit backspace or delete.  The cursor will still jump to the end

**Comment by gsteimer** [comment]
@mikeblum - any thoughts on this one?  Our current client noticed this in their DEV environment.  Is this an easy fix?

**Comment by gsteimer** [comment]
Just confirmed on edge - this happens in a normal textbox too

**Comment by mikeblum** [comment]
Revision: 12157
Author: mblum
Date: 2015-04-30 13:00:40.724934
WIZARD TEXTBOXES & TEXTAREAS: fix a rendering issue where we were updating the DOM on every key stroke and losing cursor position: https://github.com/tsgrp/ActiveWizard/issues/209

M   /uat_branches/aep-cook/app/modules/wizard/views/controltypes.js
A   /uat_branches/aep-cook/test/tests/modules/wizard/wizard/controltypes/textcontrolSpec.js

**Comment by dgrumieaux** [comment]
Still happening with some controls. Here are the controls that need to either be fixed or verify that it is fixed:
- [x] Currency
- [x] Datepicker
- [ ] Email
- [x] Number
- [x] WSYIWYG

**Comment by mikeblum** [comment]
This is now related to #212 - we need to find a middle ground between formatting text on the fly and maintaining cursor position at the same time.

**Comment by mikeblum** [comment]
---

r12572 | mblum | 2015-06-24 13:56:25 -0500 (Wed, 24 Jun 2015) | 1 line

## MERGE WIZARD FORMAT SERVICE UNIT TESTS: unit tests to support unformatting formatted values in the Wizard.

r12570 | mblum | 2015-06-24 13:52:44 -0500 (Wed, 24 Jun 2015) | 8 lines

WIZARD EVENT MANAGER + FORMAT SERVICE: large re-write of the Wizard's event bindings, validation, and on-the-fly formatting in Wisard forms. CR dgrumieaux

Closing the following github issues:
Format Service: implement a reliable way of formatting and de-formatting values #231
Fields with masks - cannot enter data properly (related to #231) #212
Text Fields - delete and backspace keys jump cursor the the end #209
Wizard Event Manger #229
