### ISSUE TITLE
Tasks are mistakenly created as serial tasks when in the same priority if different questions defined the task values

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/ActiveWizard#211]
The following case properly creates tasks in parallel:
- Multiple CR Approvers are selected on Simple CR. This works because the approvers selected are repeating values on the same question.

The following case fails to create tasks in parallel:
- Question 1's answer is Harry, Question 2's answer is Sally. Both questions trigger a workflow rule on priority 1. These are improperly created as serial tasks.

The issue is that multiple questions on the same priority are not correctly bucketed by the frontend HPI workflow evaluation code into the wizardActivities they should be in.

**Comment by dgrumieaux** [comment]
May be a dupe of https://github.com/tsgrp/hpi/issues/639

**Comment by mikeblum** [comment]
tsgrp/hpi#639 is for the case where there are multiple approvers for a single question. This issue is for separate roles (to be completed in parallel) that are on separate roles (different role names)

**Comment by mikeblum** [comment]
Tested on a client form with sequential and parallel tasks as well as Simple CR,
