### ISSUE TITLE
Fields with masks - cannot enter data properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#212]
I have a field called Project Total setup like this in the admin:

![image](https://cloud.githubusercontent.com/assets/1377228/7524354/10641498-f4c7-11e4-99e5-7368d3fcefa2.png)

When I try to type in the box in the wizard, it completely wigs out and doesn't let me type anything properly:

![currency-mask-formatting](https://cloud.githubusercontent.com/assets/1377228/7524383/4648dc2e-f4c7-11e4-9d33-a74a98123a62.gif)

It seems that the continuous formatting stuff is causing the cursor to jump to the end of the textbox.  It even gets to the point where something that looks valid still has a message saying 'Invalid Currency'.

I'm fine with ripping out the continuous formatting for questions that use an answer mask.  Would that be easier than trying to fix the continuous formatting?  @mikeblum @dgrumieaux 

@dhartman25 - this would have been nice to use for the demo form for Tuesday, but I'm thinking we'll just have to manually enter the Project Total as a currency.

**Comment by gsteimer** [comment]
Also - while doing this, we should confirm that the answer _display_ is the formatted value (ex: $5.00), but the answer _value_ is the raw data (ex: 5).

This needs to be the case since so that integer workflow rules can work properly.  I.e. - something that trips a condition if the project total is > 10000

**Comment by mikeblum** [comment]
Making this a more generic issue. Right now we listen for values to change and format like this:

``` javascript
///formattable aspect
//init formatting
this.set('displayValue', FormatService.format(this.get('value'), this.get('formatType'), this.get('format')));
//listen for changes to the value attribute and format accordingly
this.on('change:value', function(model, value){
    this.set('displayValue', FormatService.format(value, this.get('formatType'), this.get('format')));
}, this);
```

and we're formatting while a user is typing. We'll want to do this on blur instead of change:value.

**Comment by mikeblum** [comment]
Further more, we need to be more careful when a user is editing the value such as in textboxes:

``` javascript
throttleUpdate: _.throttle(function(evt){
            this.hasFocus = true;
            var text = this.$el.val();
            this.field.setDisplayValue(text);
            this.field.setValue(text);
        }, 50, this),
```

**Comment by mikeblum** [comment]
---

r12572 | mblum | 2015-06-24 13:56:25 -0500 (Wed, 24 Jun 2015) | 1 line

## MERGE WIZARD FORMAT SERVICE UNIT TESTS: unit tests to support unformatting formatted values in the Wizard.

r12570 | mblum | 2015-06-24 13:52:44 -0500 (Wed, 24 Jun 2015) | 8 lines

WIZARD EVENT MANAGER + FORMAT SERVICE: large re-write of the Wizard's event bindings, validation, and on-the-fly formatting in Wisard forms. CR dgrumieaux

Closing the following github issues:
Format Service: implement a reliable way of formatting and de-formatting values #231
Fields with masks - cannot enter data properly (related to #231) #212
Text Fields - delete and backspace keys jump cursor the the end #209
Wizard Event Manger #229
