### ISSUE TITLE
Not required Date fields are still required

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/ActiveWizard#213]
Setting a date field as "not required" does not cause the field to not be required when filling out the form.

**Comment by mikeblum** [comment]
This works when the 'master' all question required is unchecked:

![selection_020](https://cloud.githubusercontent.com/assets/3905463/8292062/ef7e0310-18f2-11e5-95f5-c72d276307fe.png)

From @benallenallen: when this switch is enabled, individual questions' require/optional settings are ignored.
