### ISSUE TITLE
Active Form is being saved with all queryable options in the persisted JSON

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/ActiveWizard#215]
This is undesireable in situations where clients have large result sets coming back from their queries.

**Comment by mikeblum** [comment]
When should this extraneous data be removed from the form? On submit/save? I'm wondering now, when we edit a form, but have changed the query, (like adding a new user to the doc base for AW Users in Group for example), I believe we re-fetch the users on bringing the form up.

**Comment by gsteimer** [comment]
In the old Active Form, we only persisted the selected options to the form XML when it was saved.  The other options were discarded and then added back in when/if the page was loaded again.

**Comment by mikeblum** [comment]
does this comment show up in slack?

**Comment by mikeblum** [comment]
r12423 | mblum | 2015-06-08 13:26:44 -0500 (Mon, 08 Jun 2015) | 1 line

WIZARD: queried options, datasources, and cached options are now removed from a form on submit & finish or on save. Unit test confirms. Closing #215

**Comment by mikeblum** [comment]
Deleting hard-coded options caused static options to fail. These need to remain persisted in the psi. We may need to look into a self-healing style where we compare the template vs the latest page set instance and add back any deleted options.

**Comment by dgrumieaux** [comment]
Does the fix for this issue also delete static options?

**Comment by mikeblum** [comment]
It does not. I'm just pointing out that if a client form as 100+ static options.. the form size would be very large. We only omit cached options, queried options, and datasource. Static options remain untouched going to the repo.
