### ISSUE TITLE
Page Set Archiver: shouldn't prompt user to overwrite each existing form when using uploadAll

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#216]
Currently, when a wizard administrator uploads a directory of Wizard psas, they are prompted to overwrite each for in the /admin directory. We should create a flag to either overrite all existing forms with the archived version or not to.

**Comment by gsteimer** [comment]
I'd say to just use the uploadAll flag for that.  No need to create a new flag, since I don't really see the case where you would want to upload a bunch of forms and then be prompted for each one...

**Comment by mikeblum** [comment]
---

r12256 | mblum | 2015-05-19 10:37:58 -0500 (Tue, 19 May 2015) | 1 line #216, #217 

Bulk Archive and Bulk Uploaf: script no longer asks for user input to archive or upload bulk forms for replacing a form or workflow rules. Fixed infinite loop of rtrying to upload a failed form as well.
