### ISSUE TITLE
Repeating table - new rows carry over text from top row

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#218]
See the screencam below.  Also note that after I took this video, I tried changing the text in row 2 and adding a 3rd row.  When I did that, the text still carried over from row 1.

![aw-repeating-table-carries-text](https://cloud.githubusercontent.com/assets/1377228/7684942/b290d8ba-fd4f-11e4-9a56-ed389320cc21.gif)

I'd like to show the new repeating table at the TSG Client Briefing on 6/1, so it would be great to get this fixed on edge sometime this week or next.  Also, would it be possible to clean up some of the items here: #121?

**Comment by dgrumieaux** [comment]
Is this on release or edge?

**Comment by gsteimer** [comment]
edge1

**Comment by mikeblum** [comment]
r12249 | mblum | 2015-05-18 11:28:33 -0500 (Mon, 18 May 2015) | 1 line

WIZARD REPEATING VALUES: displayValue wasn't getting blanked out so repeating textboxes were getting the first value propagated.
