### ISSUE TITLE
WYSIWYG - Non-Required questions are still required

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#220]
See the TS WYSIWYG page set on edge1:

![image](https://cloud.githubusercontent.com/assets/1377228/7733096/768946c8-fef2-11e4-9989-cad0b002d8cd.png)

Issues:
1. Even though the question is not required, it's still required
2. The red star shows next to the question when it should not.
3. Note that this also doesn't work on the 3rd page where the non-required question is part of a repeating table

**Comment by mikeblum** [comment]
Just like the #213 issue, the master all-questions-required option superceeds any individual question configurations.Works correctly when configured with that checkbox off. See TS WYSWIG.
