### ISSUE TITLE
WYSIWYG - Doesn't scroll

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#221]
The latest wysiwyg doesn't scroll when the text overflows the textarea:

![image](https://cloud.githubusercontent.com/assets/1377228/7734290/8d254bfe-fefa-11e4-9713-948a17d9d738.png)

**Comment by mikeblum** [comment]
r12280 | mblum | 2015-05-20 14:31:24 -0500 (Wed, 20 May 2015) | 1 line

WYSWIG: now scrollable with too much text.
