### ISSUE TITLE
WYSIWIG - copy & pasting doesn't work

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#222]
Get the following error in the console:

Uncaught TypeError: Cannot read property 'fire' of undefined

but CKEDITOR says its fixed:

https://dev.ckeditor.com/ticket/10157

Can only reproduce in Chrome, not Firefox

**Comment by grahamsinger** [comment]
I was able to get this to work in Chrome by using the latest download of CKEditor (http://ckeditor.com/download).  Not sure if this is the best fix, however.

Also worth noting that I wasn't able to copy/paste on IE 8-11, even with the latest download.

**Comment by gsteimer** [comment]
@mikeblum @RudraVishweshwar - I just tried this again and I can't get copy/paste to work on any browser (Chrome, FF, or IE11)

**Comment by RudraVishweshwar** [comment]
so ctrl +v works but when you click on the icons in the tool bar it doesnt work but the console doesnt throw any exception. with the latest version of ckeditor.

**Comment by gsteimer** [comment]
@RudraVishweshwar - `ctrl-v` does not work for me.  What browser are you using?

**Comment by RudraVishweshwar** [comment]
chrome. you have to download the lastest version n ck editor

**Comment by gsteimer** [comment]
@mikeblum @RudraVishweshwar - just so you know, I tried copy/paste using a CKEditor in Folder Notes on edge2 and it worked fine...

**Comment by mikeblum** [comment]
@RudraVishweshwar - did this fix go in along with sectional lockdown?

**Comment by RudraVishweshwar** [comment]
Yes I used the sectional lockdown branch

**Comment by mikeblum** [comment]
#265 - fixed and tested on edge.
