### ISSUE TITLE
Checkbox and Radio - Clicking label should do the same thing as clicking the checkbox / radio button

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#225]
Clicking the label text on a checkbox or radio should actually perform the click.  The user shouldn't have to click the checkbox / radio button directly.  I feel like this used to work, we even have the cursor change to a ponter when it's over the label:

![image](https://cloud.githubusercontent.com/assets/1377228/7887511/3cca259a-05f7-11e5-8539-a162b605b8c8.png)

**Comment by grahamsinger** [comment]
Fixed with rev 12647

Make the text clickable for radio buttons.  It seemed to me like this was already implemented for checkboxes, so no changes there...

CR: MB
