### ISSUE TITLE
Active Form Event Manager - Application Enhancement

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/ActiveWizard#229]
Active Wizard 5's Active Form component is largely an event driven application. Triggering and listening to events is spread ad hoc throughout the codebase of the application. Currently, a deep understanding of the codebase is required to make good decisions of where to put new triggers and listeners.

This enhancement targets collecting the disparate events into a modular structure and exposing those events as require modules. This will help making the codebase more accessible to new programmers and make adding/changing future functionality easier to do in the right way.

Talk to @mikeblum and myself before addressing this issue.

**Comment by mikeblum** [comment]
awaiting a CR

**Comment by mikeblum** [comment]
---

r12572 | mblum | 2015-06-24 13:56:25 -0500 (Wed, 24 Jun 2015) | 1 line

## MERGE WIZARD FORMAT SERVICE UNIT TESTS: unit tests to support unformatting formatted values in the Wizard.

r12570 | mblum | 2015-06-24 13:52:44 -0500 (Wed, 24 Jun 2015) | 8 lines

WIZARD EVENT MANAGER + FORMAT SERVICE: large re-write of the Wizard's event bindings, validation, and on-the-fly formatting in Wisard forms. CR dgrumieaux

Closing the following github issues:
Format Service: implement a reliable way of formatting and de-formatting values #231
Fields with masks - cannot enter data properly (related to #231) #212
Text Fields - delete and backspace keys jump cursor the the end #209
Wizard Event Manger #229
