### ISSUE TITLE
Date fields should not default to today

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#233]
See below - Blank date fields should remain blank until selected.  It should not default to today.

![image](https://cloud.githubusercontent.com/assets/1377228/8359377/84d848a0-1b2b-11e5-9080-6fa386e1812b.png)

**Comment by mikeblum** [comment]
Fixed on branch.

**Comment by mikeblum** [comment]
r12625 | mblum | 2015-06-30 13:09:11 -0500 (Tue, 30 Jun 2015) | 1 line

WIZARD DATE CONTROL: no longer defaults to today's date. Test to confirm an empty date or N/A invalidates the question. Closing #233
