### ISSUE TITLE
Select Box - Display not Correct

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#234]
When selecting a value from Simple CR's select box on page 1, here's what I see:

**In Form**
![image](https://cloud.githubusercontent.com/assets/1377228/8432178/0a118cb2-1f04-11e5-8cef-aaab1d3a0657.png)

**On Summary**
![image](https://cloud.githubusercontent.com/assets/1377228/8432181/1450ce22-1f04-11e5-8b72-295a614ff0cb.png)

**In PDF**
![image](https://cloud.githubusercontent.com/assets/1377228/8432201/410efa88-1f04-11e5-945b-8a27a246a8b5.png)

**Comment by mikeblum** [comment]
Known issue - working towards a solution on the TS Cascading Issues branch.

**Comment by gsteimer** [comment]
Can we merge this in to trunk as a separate item?  I don't want to have to wait until cascading picklists are done, if possible.  Makes demoing on edge1/2 impossible...

**Comment by mikeblum** [comment]
r12630 | mblum | 2015-06-30 13:59:58 -0500 (Tue, 30 Jun 2015) | 1 line

WIZARD: fix for #234 where typeahead and toss across answers now display as their repective displayValues on the summary page and pdf rendition.
