### ISSUE TITLE
Finish form - error flashes up

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#235]
See gif below.  Possibly related to #233 ?

![finish-form-error](https://cloud.githubusercontent.com/assets/1377228/8432212/57597156-1f04-11e5-8433-521b7e5bdc14.gif)

**Comment by mikeblum** [comment]
Need to merge in OC branch for submit timing emails though see #228 for TODOs

**Comment by mikeblum** [comment]
r12629 | mblum | 2015-06-30 13:58:42 -0500 (Tue, 30 Jun 2015) | 1 line

Fix for #235 - don't attempt to send a submit timing email without recipients.
