### ISSUE TITLE
Multi-select - Required question allows no selections

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#236]
Simple CR / Approvers is a required question, but is treated as optional.  See screenshots below

**Admin**
![image](https://cloud.githubusercontent.com/assets/1377228/8432873/4007b040-1f08-11e5-8dcb-bf8869f3fbf6.png)

**Form**
![image](https://cloud.githubusercontent.com/assets/1377228/8432888/59059ea4-1f08-11e5-8b29-463c9ab1f911.png)

**PDF**
![image](https://cloud.githubusercontent.com/assets/1377228/8432882/4e1497de-1f08-11e5-8249-283da0579a04.png)

**Comment by mikeblum** [comment]
r12646 | mblum | 2015-07-01 15:40:57 -0500 (Wed, 01 Jul 2015) | 1 line

WIZARD TS CASCADING QUERIES: overhaul of rules and placeholders in the wizard to support complex cascading query situations (see TS Cascading Queries). Closing #181, #204, #207, #206, #236, #238
