### ISSUE TITLE
Query not populating

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#237]
See screenshots below:

**AW Admin**
![image](https://cloud.githubusercontent.com/assets/1377228/8432941/a736573a-1f08-11e5-913f-2364565b4777.png)

**Form**
![image](https://cloud.githubusercontent.com/assets/1377228/8432974/d8a93c9c-1f08-11e5-9bb2-d2a808ee060f.png)

**Comment by grahamsinger** [comment]
I am seeing this working on edge2 now.  I was also able to get it to work locally to comfirm.  @gsteimer  is there something I'm missing now? @mikeblum and I think this likely got fixed when he merged last week.

**Comment by gsteimer** [comment]
Weird - I see this working too now.  Not sure what changed... I guess we can close this and keep an eye out for it.

**Comment by gsteimer** [comment]
@grahamsinger @mikeblum - Queries seem to work on edge1 and edge2 for _new_ Simple CR forms.  But when I edit an **existing** Simple CR form, here's what I see (on both edge1 and edge2):

![image](https://cloud.githubusercontent.com/assets/1377228/8600074/998dc9f6-2629-11e5-81e8-83f05fa9d2e7.png)

**Comment by grahamsinger** [comment]
Fixed with HPI revision 12672.

The substitutions (which has the group name to feed to the query) are only directly on `config` when creating a new form (not when editing an existing one), but they are always on the `config.action.attributes`.  So, we are just grabbing from there now.

CR:MB

**Comment by gsteimer** [comment]
@grahamsinger - I'm seeing this on edge1 again.  Editing an existing form gives this:

![image](https://cloud.githubusercontent.com/assets/1377228/8707861/e9351f12-2afd-11e5-8ca0-8118eb740e20.png)

**Comment by grahamsinger** [comment]
Rev. 12698

Needed to check to make sure the substitutions object had the group key/value pairs for the query, not simply if it was defined or not.  Sometimes the substitutions were defined, but were essentially blank, which caused the above error.

**Comment by gsteimer** [comment]
This is not working again on edge2.  Sometimes I see the selected options show up, but most of the time, that section is blank too.

![image](https://cloud.githubusercontent.com/assets/1377228/8779052/e25e383c-2ec6-11e5-94a0-b3d0e7e4a731.png)

Same on edge1, but the selected options are showing up more consistently.

![image](https://cloud.githubusercontent.com/assets/1377228/8779115/329ac0b8-2ec7-11e5-8696-bcb54bac9e9f.png)

@grahamsinger - can you work with @mikeblum to make sure this is fixed once and for all?

**Comment by grahamsinger** [comment]
@gsteimer yeah, this is because of #243.  This is a front end issue, not an issue with with queries specifically.

**Comment by mikeblum** [comment]
Full page reload fix solves this for the time being. #249
