### ISSUE TITLE
User Must wait until all queries are run.  Impatient users break queries.

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#239]
It seems that the HTML5 Active Form tries to run all queries when the form is loaded into the browser.  When a form has minimal queries, the user does not notice.  However, when the form has a lot of queries (like `TS Cascading Query`), it is very noticeable.  An impatient user that doesn't wait and attempts to trigger a cascading query will render the controls useless.  See screencams below.  I would also venture to guess that this will be a problem for forms that have a small amount of long running queries.

**Short Term Fix** - put some sort of "Form Loading" overlay on the screen so the user cannot work with the form until the queries are ready

**Long Term Fix** - Do not attempt to load all queries into the browser at once.  Instead, only run queries the first time a page is loaded.

_Courteous user - waits for the queries to load_
![query-proc-wait](https://cloud.githubusercontent.com/assets/1377228/8527187/ee459240-23d0-11e5-8441-8a17b7e8d7b9.gif)

_Impatient user - breaks everything_
![query-proc-impatient](https://cloud.githubusercontent.com/assets/1377228/8527192/fbbb5220-23d0-11e5-94a6-3a8e7b7ee280.gif)

**Comment by mikeblum** [comment]
r12908 | mblum | 2015-08-20 15:04:33 -0500 (Thu, 20 Aug 2015) | 1 line
Changed paths:
   M /trunk/code/app/modules/wizard/activeform.js
   M /trunk/code/app/modules/wizard/activeformrouter.js
   M /trunk/code/app/modules/wizard/events/psieventmanager.js
   M /trunk/code/app/modules/wizard/events/ruleeventmanager.js
   M /trunk/code/app/modules/wizard/models/flowpath.js
   M /trunk/code/app/modules/wizard/models/pagesetinstance.js
   M /trunk/code/app/modules/wizard/models/question.js
   M /trunk/code/app/modules/wizard/rules/queryrule.js
   M /trunk/code/app/modules/wizard/services/placeholdermanager.js
   M /trunk/code/test/tests/modules/wizard/services/placeholdermanagerSpec.js

Fix for issue #239 - queryable questions in the Wizard now load as the user browses to that page, not all at once. Looking at the network tab should show the 'horse races' of queries to be no more. Passes TS Cascading Query and Simple CR with unit tests. CR dgrumieaux.

![selection_054](https://cloud.githubusercontent.com/assets/3905463/9394329/7dedd2a0-474d-11e5-9790-6f5acee6e829.png)
