### ISSUE TITLE
Options don't properly populate from query after first time

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/ActiveWizard#243]
Strongly related to #204.

The field options don't properly get put into the control after the first time loading a form.  The query come back fine from OC, so that's not the issue.

The issue is that after the first time, inside the `datasource.fetch().done()`, the listeners aren't the same as the first time, so the control (in this case a `MultiSelect`) doesn't get re-rendered with the options.

If you 'Save & Exit' then go to re-edit this doesn't happen because the options are preserved on the field: i.e. `this.field.get('allOptions')`

I have replicated the issue on both DCTM and Alfresco.

See below:
![formoptionssecondtime](https://cloud.githubusercontent.com/assets/8784597/8659969/d9a717f2-2973-11e5-9054-2fa752937a91.gif)

**Comment by gsteimer** [comment]
If I understand this correctly, you basically can only create a form once before needing to refresh the page, correct?  I'm seeing that behavior on edge1 and edge2.  After I create a form, I have to logout or refresh the page in order to be able to create a new form from the same template.  Just want to make sure this is the same thing.

**Comment by grahamsinger** [comment]
Yeah that's correct.

**Comment by mikeblum** [comment]
I think this has to do with us not properly cleaning up our views in the following scenarios:
- editing an existing form
- creating a new form of the same template as a previous form

This makes sense as examining the network tab shows that our models are correctly getting parsed, querying, etc but the views don't appear to be updating properly.

**Comment by dgrumieaux** [comment]
As a short term workaround solution, it's possible that we could reload the page (window.location = the url) when we hit a new form route - just like we do in Security.logoff. This isn't a very single page app like behavior, but it would solve the bug in the meantime.

**Comment by grahamsinger** [comment]
Yeah, I've implemented the suggestion above locally and this issue along with #204 get resolved, however, as would be expected the performance is a bit clunkier.

**Comment by grahamsinger** [comment]
Addressed with rev.12711

After discussing with @mikeblum this is an OK temporary workaround solution for this and #204 since these errors are quite obvious and annoying.

A fix to strive for would be one that can properly clean and re-do the views and listeners without having to reload the page on subsequent visits to a form.

@gsteimer im not sure if you want to close this and open a new ticket with the above enhancement or keep this and #204 open.

**Comment by gsteimer** [comment]
@grahamsinger - lets close these to keep things organized better.  Create the new enhancement with a 2.4 milestone.  I think it's worth it to pursue the better solution for a better user experience.
