### ISSUE TITLE
Required File Input - Page never validates correctly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#246]
A required file input never validates to true.  See screenshots from Simple CR on edge1:

Notice one file was selected, but no green checkmark for the page:
![image](https://cloud.githubusercontent.com/assets/1377228/8683026/e80e1c24-2a35-11e5-80a8-18e5dc7c5f47.png)

On the summary page, the system still thinks the page is invalid:
![image](https://cloud.githubusercontent.com/assets/1377228/8683036/f51995d8-2a35-11e5-935c-cc0041d30a78.png)

**Comment by ghost** [comment]
Fixed by adding the change trigger which lets the validation know that it needs to update
HPI - 12694
CR - Blum
