### ISSUE TITLE
Ability to lead to a page from two different pages

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#247]
Many forms have the following scenario:
- Page 1 can lead to Page 2
- Page 1 can lead to Page 3
- Page 2 can lead to Page 3

This scenario will result in the following page flows:
- P1 -> P3 (leading action to page 2 _was not_ tripped)
- P1 -> P2 -> P3 (leading action to page 2 _was_ tripped)

I tried setting up this scenario on edge1 using `TS Leading Actions` and it _mostly_ worked.  Basically, the issue was that in the last scenario the pages were out of order.  It was P1 -> P3 -> P2 (with the P3 page being inserted after answering the correct question on P2).

Once this is finished, I also have a client form that I'd like to try this out on too.

**Comment by mikeblum** [comment]
Here's the error to re-produce:

![selection_025](https://cloud.githubusercontent.com/assets/3905463/8827566/12267916-3053-11e5-86fe-fa6f4801c108.png)

When this is fixed, we should see Page 7 followed by Page 21 followed by Page 20 since page 7 lead to page 21 which then lead to page 20. I think somewhere along the line the pages are getting put in ascending order and we don't want that.

**Comment by mikeblum** [comment]
r12740 | mblum | 2015-07-27 09:46:59 -0500 (Mon, 27 Jul 2015) | 1 line

partial fix for #247. TS Leading Actions OK with unit tests. Issue remains for leading to a page from other pages with logically conflicting answers (one page says yes and the other says no)

**Comment by mikeblum** [comment]
One approach to solving the conundrum of multiple pages leading to a single page would be to lead to a page if the user answers Yes. But this brings up the complication of designating a question as answered truthfully or not. consider the following:

_Page 1_
Omit Marketing Team: Yes

_Page 2_
Notify the following teams:
- IT Operations
- Marketing
- Procurement

_Page 3_
Notify Marketing
...

In this situation the first page says not to notify marketing but the second page does. Which one wins here?

**Comment by gsteimer** [comment]
I vote that as soon as a leading action is tripped, then the page should display.  If there are logical fallacies in the page flow then the admin should re-architect the form.  In your above example, we'd just say to remove _Page 1_

**Comment by mikeblum** [comment]
Here's the example flowpath schema that's failing.. you see there's a conflict with visibility with page 3:

``` javascript
[
  {
    "id": "pg0",
    "visible": true,
    "children": [
      {
        "id": "pg1",
        "visible": true,
        "children": [
          {
            "id": "pg4",
            "visible": true,
            "children": [
              {
                "id": "pg2",
                "visible": true,
                "children": []
              },
              {
                "id": "pg5",
                "visible": false,
                "children": []
              }
            ]
          },
          {
            "id": "pg2",
            "visible": false,
            "children": [
              {
                "id": "pg3",
                "visible": true,
                "children": []
              }
            ]
          }
        ]
      },
      {
        "id": "pg3",
        "visible": false,
        "children": []
      }
    ]
  }
]
```

**Comment by mikeblum** [comment]
Going to close this until a new client form arises that breaks the fix comitted above.

**Comment by gsteimer** [comment]
According to @aviking - this is still an issue.  Avi - can you commit when you get the chance?

**Comment by aviking** [comment]
Closed with OC Commit: 16909

CR: George S.
