### ISSUE TITLE
Don't trigger a page refresh every time a new form is created.

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/ActiveWizard#249]
Instead of calling `window.location = ...` we should be able to enter a form and have our views/listeners get set up in a way that works.  It is very likely that we are not cleaning up these views/listeners appropriately when existing a form.

This is a better way to handle the fix for #204 and #243.

**Comment by gsteimer** [comment]
@grahamsinger - Since this isn't really an Active Form thing, I'm going to move this to the HPI GitHub
