### ISSUE TITLE
Support unlimited chaining of non-required pages

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#254]
There are issues in flowpath.js addPage and removePage functions for adding and removing greater then 2 pages deep of pages. Consider the following scenario:

Page 0 <-- required
|_ page 1
             |_ Page 2
             |            |_ Page 3
             |                         |_ Page 4
             |_ Page 3
                           |_ Page 4

Turning off page 3 should remove Page 4 from the flowpath but doesn't. The most likely culprit is that the removePage algorithm is only checking one level deep of a page's children.

**Comment by mikeblum** [comment]
r12901 | mblum | 2015-08-19 14:55:53 -0500 (Wed, 19 Aug 2015) | 1 line

WIZARD - LEADING TO SEVERAL NON-REQUIRED PAGES #254. TS Subtrees works but having multiple sets of the same page being lead to causes issues.. see GH issue.

**Comment by mikeblum** [comment]
is the above scenario I have laid out an actual situation?

**Comment by mikeblum** [comment]
after talking to @benallenallen the scenario laid out above doesn't appear to be supported.

What is supported is the following:

``` javascript
Page 0 <-- required
    |_ page 1
        |_ Page 2
            |_ Page 3
    OR
    |_ Page 4
        |_ Page 5
            |_ Page 6
```

**Comment by gsteimer** [comment]
@mikeblum - so wait, we still don't support the fololwing?:

``` javascript
Page 0 <-- required
    |_ page 1
        |_ Page 2
            |_ Page 3
            |_ Page 4
        |_ Page 5
            |_ Page 6
```

Basically, a non required page leading to more than one page.  If that's not supported, I don't think we can close this issue.
