### ISSUE TITLE
IE 9: radio buttons arn't triggering validation or rules

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#255]
It appears along the way radio button listeners in the controltypes.js are incompatible with IE 9. Wasn't able to reproduce in IE 10.

**Comment by gsteimer** [comment]
I'm fine with making this Upon Client Request.  Hopefully we don't see much IE9 going forward, and if we do, we can say that their forms can just use selects rather than radio buttons if they don't want to have us fix this issue.

**Comment by mikeblum** [comment]
need to get this working for a demo.

**Comment by mikeblum** [comment]
r13605 | mblum | 2015-10-29 17:25:58 -0500 (Thu, 29 Oct 2015) | 1 line
Changed paths:
   M /trunk/code/app/modules/wizard/views/controltypes.js

WIZARD + IE 9: Support for radio buttons in IE 9 and uploading supporting docs. For some reason this issue with supporting docs has been stealthy up to this point. Here is an interesting article as to why the assumption of having a listener doesn't work. http://missioncriticallabs.com/blog/lessons-learned-from-jquery-file-upload
