### ISSUE TITLE
Forms without an autonumber - name not picked up at the start of form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#257]
See the screencam below:

![form-naming](https://cloud.githubusercontent.com/assets/1377228/9470980/f0bfce7c-4b13-11e5-9d72-69dc415fdd00.gif)

**Comment by grahamsinger** [comment]
Fixed with rev12937

The form name was correctly being passed in as a param and into wizard context. But the wizard context params get reset on every new page so the `reservedName` gets cleared out.  Now, we just set it on the first page to make sure it persists.

CR: MB
