### ISSUE TITLE
Stop pages no longer stop

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#258]
See the screencam below.  Shouldn't a page without questions be considered a Stop page and prevent the user from finishing the form?

![stop-page](https://cloud.githubusercontent.com/assets/1377228/9471131/892dd122-4b14-11e5-86f1-d2a74a8fc00e.gif)

@mikeblum

**Comment by gsteimer** [comment]
Also note that the screencam above shows incorrect behavior described in #257

**Comment by dgrumieaux** [comment]
That's interesting since the page is still marked invalid. Technically that's all a STOP page is - an invalid page. I would be interested to see how this behaves if it was the second page of a form, and concerns me that any kind of invalid page no longer stops a user from completing.

**Comment by gsteimer** [comment]
I don't think we need to worry about your larger concern.  I just tried it out with Simple CR:

![image](https://cloud.githubusercontent.com/assets/1377228/9471367/8e9df366-4b15-11e5-99b0-ca9447e372ce.png)

My guess is that this is just an issue with Stop pages, and possibly this edge case of _only_ having a single page with no answers.  Which obviously doesn't make sense.  @mikeblum do you remember why `TS Single Page` was configured with no questions?  I think we should have at least one question on there, and then a separate `TS Stop Page` to test stop pages.

**Comment by gsteimer** [comment]
Yeah - this is definitely an issue with Stop pages.  I created `TS Stop Page` out on edge1 (I'll move it to edge2 in a sec):

![image](https://cloud.githubusercontent.com/assets/1377228/9471614/d2b91408-4b16-11e5-8959-1c518bf8c68c.png)

Even though I see a stop page, I can finish the form...

**Comment by gsteimer** [comment]
Interestingly, if I actually do try to finish the form, I get an error:

![image](https://cloud.githubusercontent.com/assets/1377228/9471648/f224f67c-4b16-11e5-9af1-c968ba100990.png)

**Comment by mikeblum** [comment]
So this looks like a validation issue with stop pages in particular.

**Comment by mikeblum** [comment]
r13525 | mblum | 2015-10-23 10:52:42 -0500 (Fri, 23 Oct 2015) | 1 line

WIZARD - STOP PAGES: a page with no questions is now invalid. Issue: https://github.com/tsgrp/ActiveWizard/issues/258
