### ISSUE TITLE
Notifications should go to the owner of the form rather than the initiator of the workflow

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/ActiveWizard#26]
Many clients have shifts of users that need to be notified of activity rather than the initiator of the workflow. Currently, the wizard sends all notifications to the workflow initiator. The core product should instead use some kind of "owner" attribute on the form to determine who gets the notifications instead of the initiator. This would have to be done in conjunction with a "Change Owner" action to be able to change ownership of the form and all notifications to somebody else.

**Comment by gsteimer** [comment]
This is configurable now as of HPI 2.3 with the following OC property: `wizard.workflow.email.sendToInitiator`.
