### ISSUE TITLE
TS Calculations and TS Cascading Query - Questions are disabled when they shouldn't be

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#260]
See TS calculations on edge1 and edge2.  It seems that a bunch of questions that should be editable in the admin are uneditable in ActiveForm.  For example:

Admin:
![image](https://cloud.githubusercontent.com/assets/1377228/9551094/b37edf0e-4d74-11e5-8873-6f6e8b084747.png)

ActiveForm:
![image](https://cloud.githubusercontent.com/assets/1377228/9551106/bf69baf0-4d74-11e5-9e5d-ae93d595904b.png)

**Comment by gsteimer** [comment]
Note - I also see this on many other pages in the TS Calculations form.

**Comment by grahamsinger** [comment]
Fixed unit tested, awaiting CR.

**Comment by mikeblum** [comment]
![selection_057](https://cloud.githubusercontent.com/assets/3905463/9635435/159fc7da-515c-11e5-874a-e9cc36d7ebe0.png)

On edge1, TS Cascasing Queries the first textbox that starts the chain of cascading queries is disabled. Removed the disabled class from the markup seems to work.

**Comment by grahamsinger** [comment]
Fixed with rev12993.

We now have proper handling for when `disabled` is undefined in the PSI JSON. Unit Tested.

CR:MB
