### ISSUE TITLE
HTML Tags display in page description on status pane

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#263]
See the screenshot below.  If you have HTML tags in your page description, they show up in the status pane:

![image](https://cloud.githubusercontent.com/assets/1377228/10084516/7877cd3e-62c9-11e5-9c9b-50ef59ffa8b2.png)

I understand why we do that - since the status pane cuts off the description,  we don't want to display invalid HTML on the page (which would screw up the rest of the page markup).

Instead of just displaying HTML tags, we should do this:
1. Strip off any html from the page description.  I'm sure there's a way to do this with jQuery or another library we already pull into HPI...
2. Display the first N chars in the page description and the `...` if necessary.

**Comment by mikeblum** [comment]
I would argue since the help text div already copes with HTML markup, the page description and other areas should do the same. Super easy fix to add {{{ }}} around that div in the html template. I think right now its just {{ }} (2 vs 3 curly braces). Its like a 2 sec fix. 

http://stackoverflow.com/a/20280656/1377866

**Comment by gsteimer** [comment]
@mikeblum - yeah, that's a better solution, assuming it accommodates the way we cut off the description.  For example, in my screenshot, the text ends with `<u...`.  If we were to use your approach, is there a chance the markup would get messed up from a cut-off description?

**Comment by mikeblum** [comment]
Ah yes, I forgot we truncated descriptions. I think we already expect html but don't account for the truncation scenario. One interesting case will be if an HTML-escaper like $jQuery can correctly escape invalid markup like what you have above or if it becomes a borked string.

**Comment by gsteimer** [comment]
I was thinking we'd strip the HTML first and then truncate to avoid that issue...

**Comment by mikeblum** [comment]
right you are.

We'll just want to make sure we don't strip the html markup for the full description that the user sees when they go to a page (what we see below the title there)

**Comment by mikeblum** [comment]
Escalating this to high priority as I just got an email from a client pointing out this issue.

**Comment by renesaladrigas** [comment]
ACTIVE FORM -- Tags are no longer displayed in the page description on the status pane and the message is truncated to 78 chars.

CR - MBlum
Fixed with revision #13203

**Comment by renesaladrigas** [comment]
Corrected previous commit to pass unit tests that were failing.
Revision #13205
