### ISSUE TITLE
Disabled Controls

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#265]
Right now only Textboxes and typeahead controls can be disabled by configuration in the AW Admin:
- [x] Textboxes
- [x] Text Areas
- [x] Dateboxes
- [x] Typeahead
- [x] Radio buttons
- [x] Checkboxes
- [x] Toss-Across (this is a complicated one)
- [x] WYSWIG (also pretty interesting)
- [x] Number
- [x] Email
- [x] Telephone
- [x] Multi-Text input (disable adding and removing values)
- [x] Files
- [x] Grouped Questions (Table Questions) - only during Sectional Lockdown - see TS Sectional Lockdown for an example.

We want to complete this list and update TS Disabled Controls to be feature-complete. See me to get the feature branch that has this effort on it.

**Comment by mikeblum** [comment]
r13369 | mblum | 2015-10-13 16:29:25 -0500 (Tue, 13 Oct 2015) | 1 line
Changed paths:
   M /trunk/code
   M /trunk/code/app
   M /trunk/code/app/modules/common/tossacross.js
   M /trunk/code/app/modules/wizard/activeform.js
   M /trunk/code/app/modules/wizard/activeformrouter.js
   M /trunk/code/app/modules/wizard/formfields/aspects.js
   M /trunk/code/app/modules/wizard/formfields/fieldfactory.js
   A /trunk/code/app/modules/wizard/formfields/temporaryaspects.js (from /feature_branches/wizard_sectional_lockdown/app/modules/wizard/formfields/temporaryaspects.js:13320)
   M /trunk/code/app/modules/wizard/models/field.js
   M /trunk/code/app/modules/wizard/models/page.js
   M /trunk/code/app/modules/wizard/models/pagesetinstance.js
   M /trunk/code/app/modules/wizard/services/pagesetinstanceprovider.js
   A /trunk/code/app/modules/wizard/services/sectionallockdownservice.js (from /feature_branches/wizard_sectional_lockdown/app/modules/wizard/services/sectionallockdownservice.js:13320)
   M /trunk/code/app/modules/wizard/views/abstractcontrol.js
   M /trunk/code/app/modules/wizard/views/controltypes.js
   M /trunk/code/app/modules/wizard/views/flowpathview.js
   M /trunk/code/app/modules/wizard/views/navigationcontrolsview.js
   M /trunk/code/app/modules/wizard/views/pagesetinstanceview.js
   M /trunk/code/app/modules/wizard/views/pageview.js
   M /trunk/code/app/modules/wizard/views/psiheaderview.js
   M /trunk/code/app/modules/wizard/views/summaryview.js
   M /trunk/code/app/templates/common/tossacross/filter.html
   M /trunk/code/app/templates/common/tossacross/item.html
   M /trunk/code/app/templates/common/tossacross/tossacross-mainlayout.html
   M /trunk/code/app/templates/formfields/checkboxescontrol.html
   M /trunk/code/app/templates/formfields/datepicker.html
   M /trunk/code/app/templates/formfields/radiocontrol.html
   M /trunk/code/app/templates/search/quicksearch.html
   M /trunk/code/app/templates/wizard/psi-header.html
   M /trunk/code/app/templates/wizard/tablequestiongroupcontrols.html
   M /trunk/code/app/templates/wizard/verticalquestiongroupcontrols.html
   M /trunk/code/app/templates/wizard/wyswigcontrol.html
   M /trunk/code/assets/css/styles/hpi.styl
   M /trunk/code/project
   M /trunk/code/test/tests
   M /trunk/code/test/tests/modules/wizard/formfields/formfieldsSpec.js
   M /trunk/code/test/tests/modules/wizard/services/pagesetinstanceproviderSpec.js
   A /trunk/code/test/tests/modules/wizard/services/sectionallockdownserviceSpec.js (from /feature_branches/wizard_sectional_lockdown/test/tests/modules/wizard/services/sectionallockdownserviceSpec.js:13320)
   M /trunk/code/test/tests/modules/wizard/wizard/views/navigationcontrolsviewSpec.js

SECTIONAL LOCKDOWN: support for disabling all the control types for the Wizard and the various Sectional Lockdown scenarios.

**Comment by gsteimer** [comment]
@mikeblum @RudraVishweshwar - I cannot edit an existing form on edge1 or 2.  All of the fields are disabled, even though the form is in Draft:

![image](https://cloud.githubusercontent.com/assets/1377228/10516620/c3de3c3a-731e-11e5-9591-699f49086c28.png)

![image](https://cloud.githubusercontent.com/assets/1377228/10516632/d0979bc4-731e-11e5-8580-b805a8d49a27.png)

**Comment by gsteimer** [comment]
with @mikeblum's recent updates, I can now create a form and edit it.  However, if I try to edit a form that I created before the updates, it still is showing disabled controls.

**Comment by gsteimer** [comment]
Also - while looking at the disabled controls, I noticed there's an issue with disabled radio buttons.  The actual radio button is correctly disabled and not changeable, but clicking on the button label changes the value fine.  See the gif below.  We need to validate this works properly for checkboxes as well.

![aw-disabled-radio](https://cloud.githubusercontent.com/assets/1377228/10518367/b1011b98-7326-11e5-92d8-4166f9305415.gif)

**Comment by mikeblum** [comment]
so it appears there was a bug in the page set instance provider that i fixed in the sectional lockdown but all fields were getting the disabled aspect silently.

``` javascript
//disabled aspect
                        if(inputJson.disabled === undefined || inputJson.disabled.value === false){
                            fieldAspects.push('disabled');
                            question.disabled = false;
                        }
                        else if(inputJson.disabled.value === true){
                            fieldAspects.push('disabled');
                            question.disabled = true;
                        }
```

This has since been fixed for new forms going forward. The only current solution is to edit the json manually for older forms with this issue.

**Comment by mikeblum** [comment]
Looking at the SVN logs it appears this issue affects forms created between 8/10/2015 and 10/13/2015. Shouldn't affect any clients.

**Comment by mikeblum** [comment]
Since there are no code changes to fix this I'll close it.

**Comment by gsteimer** [comment]
@mikeblum - we can't close this until the errors with radio (and possibly checkbox) are fixed.

**Comment by RudraVishweshwar** [comment]
Fixed with revision 13406. Radio Buttons and Checkboxes now work with disabled controls.
