### ISSUE TITLE
Sectional Lockdown - ability to restrict a page to all users

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#268]
When using Sectional Lockdown, there is no way to denote that a page should be locked down for all users.  If, on the page, you simply do not configure any roles, this causes the page to always be editable (which is what we want).

This enhancement would give the admin a way to denote that the page should be locked down for all roles/users.

**Comment by gsteimer** [comment]
As a workaround in the meantime, you could simply define a role that is never tripped in the form, and then give that role edit access to the page.

**Comment by mikeblum** [comment]
Could we support just checking the Sectional Lockdown checkbox and then adding no roles and support that configuration in the Wizard?

**Comment by gsteimer** [comment]
Yep - that's what I tried to do in the admin, but when you go to save the page like that the code unchecks the box, so it's impossible.

**Comment by gsteimer** [comment]
Ok - I was getting confused on this one.  We're ok here.  Here's how Sectional Lockdown works:
1. If no pages are locked down, all pages are open
2. As soon as one page is locked down to a role, all pages that do not have sectional lockdown configured are locked down.  Essentially - editing becomes opt in, which makes this issue moot.
3. If you want all roles to be able to edit a page, just add all roles to the sectional lockdown list.
   - Note - per e-Signature requirements, after one user signs off, any other users will be locked out of the form.
