### ISSUE TITLE
Supporting Docs - Remove confirmation message does not show document name

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#270]
See the screenshots below:

**Attached Document**
![image](https://cloud.githubusercontent.com/assets/1377228/10544133/51417920-73e7-11e5-8a22-2eb9d259cf2e.png)

**Remove Confirmation Message**
![image](https://cloud.githubusercontent.com/assets/1377228/10544151/61e5cee8-73e7-11e5-85b1-75ffd168af16.png)

**Comment by RudraVishweshwar** [comment]
Fixed with revision 13410. The alert box now displays document name.
