### ISSUE TITLE
Option to auto-signoff when wf initiator is approver on his own form

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/ActiveWizard#271]
Basically, you shouldn't have to sign off on your own Change Request in some client scenarios. It would be nice to work like Replicon's approval system where the auto-approve happens when you're submitting your own timesheet. This should be possible using the Activiti listeners.

**Comment by dgrumieaux** [comment]
We would want this to be configurable to be on or off, though, some clients will want to still have people sign off manually on their own tasks. Especially when the workflow has users changing the documents or the change requests throughout the process of approval.

**Comment by gsteimer** [comment]
@dgrumieaux - technically this should go in the HPI GitHub - I'd like to reserve this one for Active Form and AW Admin...

**Comment by dgrumieaux** [comment]
@gsteimer - ok sounds good. i'll close here and open there.

**Comment by dgrumieaux** [comment]
https://github.com/tsgrp/hpi/issues/857
