### ISSUE TITLE
Folder Property Inheritance - Property Integrity Over Time

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#273]
When a client sets up folder property inheritance, we currently have nothing that keeps the integrity of the properties updated over time.  For example, for the Insurance reference trac - this scenario can occur:
1. Admin sets up policy documents to inherit from the Policy Folder
2. User checks in documents, certain values like policy number, insured name, etc. inherit down to the document.
3. At some later point in time, one or more of the folder properties change on the document.  Example - the Insured Name changes
4. The document(s) in the folder now have an incorrect insured name

Up to this point, we have not added anything to core HPI to keep the properties in sync for a number of reasons:
1. Some client's don't want the properties to synchronize - in this case, the inheritance is more of a 
2. Some clients use the PropertyIntegrityCheck to sniff out these inconsistencies and manually update them

We should talk before implementing this, but here are some ideas:
- We could do this with a nightly job or a TBO/Behavior.  Pros and cons with both approaches.
- One of the biggest things here - how do we target a common core folder type?  Do we need to create an `hpi_folder` object type or something like that?

**Comment by zkeller** [comment]
While it isn't through HPI or OC code, for alfresco, we have the folder inheritance amp that was recently updated to keep folder and document property values in sync when the folder values change. It does that through a behavior.

**Comment by gsteimer** [comment]
@zkeller - Interesting, is it configurable enough to handle any client scenario?

@joehof @dhartman25 - Dave was asking me to add this for your current client.  Can we just use the AMP Zaq mentioned and call it good?

**Comment by zkeller** [comment]
It is pretty generic - in a props file in the amp you specify the properties/aspects that are inherited, and you list the types you want to run the behavior on, then you set up the folder inheritance rule on the folder (which syncs up properties when a document enters the folder).

**Comment by gsteimer** [comment]
@zkeller - nice, thanks.  @joehof / @dhartman25 - can either of you verify if this will work for your current client as-is or do we need any more development time?

**Comment by dhartman25** [comment]
@gsteimer - this sounds like it should satisfy what our client needs.

**Comment by gsteimer** [comment]
Closing - moved to https://github.com/tsgrp/hpi/issues/869
