### ISSUE TITLE
Wizard Form Owner changed to the Logged-In User after editing a form

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#274]
When a wizard form is edited, the Owner Name is updating to the currently logged in user. Shouldn't this stay as the initial form initiator rather then updating to follow the latest form editor?

**Comment by benallenallen** [comment]
Form owner = last person to edit it
Creator = person that created the form initially (never changes once set)
Workflow Initiator = user that started the workflow

@gsteimer - agree?

**Comment by mikeblum** [comment]
![selection_088](https://cloud.githubusercontent.com/assets/3905463/10694644/f00ab68e-7964-11e5-81e4-8d6d9c658850.png)

Got confused with the naming.

Looks like form owner and creator are working as expected. Closing..

**Comment by gsteimer** [comment]
@benallenallen @mikeblum - let's talk about this more during next week's AW meeting.  I feel like different clients will want this to behave differently.
