### ISSUE TITLE
Timing Emails - Form PDF attached to email does not have view time overlays

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#280]
When sending timing emails, the form PDF gets attached to the email.  However, view time overlays are not applied  (Ex: form status in the top right)

![image](https://cloud.githubusercontent.com/assets/1377228/11010019/74c05cf2-84a1-11e5-9b7e-d99a36b32b22.png)

**Comment by gsteimer** [comment]
Sounds like this is an issue with the overlay config vs. anything code related.  We need to include the `ocEmail` restriction and set it to `true`

@benallenallen - can you check to see if there's a way to do this with one overlay rather than duplicating?  You mentioned something about a client doing something with regex...

**Comment by gsteimer** [comment]
Looks like one client has something like this:

``` xml
<restriction key="effectiveDate" value="^(?=\\s*\\S).*$"/>
```

This isn't exactly what we want, but at least shows us that regex is possible in the overlay restriction value.  We essentially want something that says:  Accept the restriction as true if `ocEmail` is blank/null OR 'true'.  Once we figure that out, we won't have to duplicate the overlays to handle this issue.

**Comment by renesaladrigas** [comment]
OPENOVERLAY: adding ocEmail restrictions to aw_attached_docs as well as Wizard Page_Set_Instances and simple_cr so overlays are applied to email attachments for timing emails in the Wizard.

CR - MBlum
Revision 13166
