### ISSUE TITLE
Forms Restricted to only Wizard Administrators

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/ActiveWizard#283]
Running trunk OC, HPI, and Alfresco 4.2.1, in the wizard-alfresco project, I encounter an issue where only wizard administrators are able to create a Simple CR, where the form was created using the psa tool and the Simple CR available in HPI setup-aw. 

Screenshot of wizard administrator able to create form:
![image](https://cloud.githubusercontent.com/assets/14186924/12039221/13ed6bac-ae24-11e5-96c9-fec507a3e74c.png)

Screenshot of wizard contributor unable to create form:
![image](https://cloud.githubusercontent.com/assets/14186924/12039237/34a310d6-ae24-11e5-9c22-b89a4503f2cb.png)

This is unlike running Alfresco 5.0.1 - in Alfresco 5.0.1, no user can create the form.

**Comment by gsteimer** [comment]
@ZachGerth - I just tried creating a Simple CR on edge2 with a non-AW admin user and it worked fine.  I think this is an issue with your environment, and not a code problem.  Feel free to reopen this if you disagree.
