### ISSUE TITLE
New Hidden Question option doesn't default properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#294]
See the screencam below - when a question doesn't have the new "Make this question Hidden" option selected, saving the page (without choosing a hidden value) defaults the question to hidden.

![aw-form-admin-hidden-default](https://cloud.githubusercontent.com/assets/1377228/18018560/3b94cd80-6b9d-11e6-9f36-656069eb63d5.gif)

**Comment by alieblich** [comment]
fixed with rev#7714
