### ISSUE TITLE
1.0 Effective version incorrectly shows Form attachment to 1.x's form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#42]
Scenario setup:

1. 1.0 Doc was approved on SCR-014
2. 1.x Doc is currently routing for approval and attached to SCR-015
3. When viewing 1.0 Document in the stage, the stage incorrectly shows BOTH forms as related forms.  1.0 should only be attached to SCR-014

![doc-versions-refresh](https://f.cloud.github.com/assets/1377228/1933228/14cd9614-7ed8-11e3-80d4-3c5d2c74db66.gif)

Note, the above gif also has this HPI bug present: https://github.com/tsgrp/hpi/issues/118

**Comment by dgrumieaux** [comment]
This bug was also found to be a non issue and was due to a misconfiguration of the workflow document relationship name. See #89. After configuring the correct relationship name, this was no longer a problem on edge1. Removing the issue tag and closing.

**Comment by gsteimer** [comment]
@dgrumieaux - I tried this again on edge1 and I'm still seeing the issue.  I have TSG-106 1.0,Effective attached to SCR-124.  Then I created TSG-106 1.1, Draft and attached it to SCR-125.  Here's what I see in the stage:

1.1 - correctly attached to SCR-125
![image](https://cloud.githubusercontent.com/assets/1377228/6238250/16ddb2c0-b6bf-11e4-8b21-2f7c5ecad85e.png)

1.0 - Shows that it is attached to SCR-124 AND 125
![image](https://cloud.githubusercontent.com/assets/1377228/6238258/275c578c-b6bf-11e4-89ab-d21ee7c3e6fd.png)

Marking this as high priority again since I think it'll be an issue for our current client project

**Comment by dgrumieaux** [comment]
Fixed in OC rev 10911.

---SVN Comment below---
DCTM FROZEN RELATIONSHIPS - corrected DCTMExtendedContentImpl#getRelatedParents to properly not display relationships where a frozen relationship's child_label did not match any of the parameterized document's symbolic labels. See code comments for more detail.

Fixes the elusive ActiveWizard/issues/42. Reviewed by @ballen

**Comment by gsteimer** [comment]
@benallenallen @dgrumieaux - I took a look at the code.  It looks like the query was changed to this:

``` SQL
String dql = "SELECT r_object_id, child_label, parent_id FROM dm_relation where child_id='" + doc.getChronicleId() + "' "
                    + "AND child_label IN (select r_version_label from dm_document (all) where r_object_id='" + objectId + "')";
```

While this will work, querying against `dm_document (all)` is never a good idea.  We already have the object in an `IDfSysObject` from line 673  why not change the query to use the labels returned by `doc.getVersionLabels()` instead?  I know it's super annoying that that method returns an `IDfVersionLabels` object and we'll have to iterate over the labels to build up a comma separated list, but I still think that's better than querying against ALL documents and ALL versions in Documentum, which is often slow on large client docbases.

**Comment by dgrumieaux** [comment]
Committed fix to address @gsteimer 's comment issues in OC rev 10951. SVN comment below:

DCTM FROZEN RELATIONSHIPS - updated code to not make an inefficient query, and instead uses the existing IDfSysObject to retrieve the r_version_labels.

REALLY fixes the elusive ActiveWizard/issues/42. Reviewed by @gsteimer
