### ISSUE TITLE
Wizard Signature Page File Reference vs Resource Injection

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/ActiveWizard#47]
If OC is deployed non-exploded (for instance in a Weblogic/Websphere environment), OC's Spring initialization fails when trying to inject our path in as a File type variable into the Signature Page class.
Scenarios to test:

- [ ] Exploded
- [ ] Not Exploded

When finished testing,

- [ ] Merge change into trunk

**Comment by gsteimer** [comment]
Closing this.  Looking at the alfresco and dctm versions of the bean config, it looks like we pull in the signature template via classpath now:

``` xml
<property name="templateLocation" value="classpath:eSignatureTemplate.htm" />
```

@benallenallen @dgrumieaux - feel free to re-open this if I'm missing something.
