### ISSUE TITLE
dm_world user cannot see document actions on non-LATEST document

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#51]
Steps to reproduce:

- Version an Effective document from a major version to the next minor (ex 1.0 to 1.1)
  - the 1.0 will be CURRENT, the 1.x will be LATEST
- Login as a dm_world user.  This user should not be a wizard_administrator, wizard_contributor or a wizard_doc_editor
- Search for the document, the correct 1.0 version only displays
- Load the document into the stage.  See screenshot below.  The loading message is never replaced with valid actions.

![image](https://f.cloud.github.com/assets/1377228/2201304/2fe3f28e-98ed-11e3-96eb-76ac40d3bd44.png)

**Comment by dgrumieaux** [comment]
This error occurs when a condition evaluator throws a runtime exception. This needs retesting, but seems likely to me that this is no longer a problem.

**Comment by gsteimer** [comment]
Not sure on the revision, but this is no longer an issue with HPI 2.3 on edge1.
