### ISSUE TITLE
Cannot Edit a Document or Form During Review or Approval Route

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#86]
For some reason, when you edit a document while in a review route, the document goes back to Draft upon checkout.  Once you checkin the document, completing a review route will fail due to #72 

The high priority item here is getting edit in review working, which is the more common case.  Having edit during Approval will need to be done eventually, but it isn't as high priority as edit in review.

This is only an issue in Alfresco since the error stems from our behavior code.  Side note - it's odd that this happens on checkout.  I would think that it would happen on checkin.  Could it be something to do with the working copy perhaps?

**Comment by gsteimer** [comment]
This issue is getting confusing to read, so here's the cases we need to test and make sure work:

**Documentum**
- [x] Edit a form during the review route
  - Fails on edge1 with this error: `Failed to update workflow definition for 0900000880022e6c`
- [x] Edit a form during the approval route (should not re-evaluate workflow rules and modify workflow definition)
  - Fails on edge1 with the same error as edit during review, and does try to re-evaluate rules
- [x] Edit a controlled document during the review route
- [x] Edit a controlled document during the approval route

**Alfresco**
- [x] Edit a form during the review route
- [x] Edit a form during the approval route (should not re-evaluate workflow rules and modify workflow definition)
- [x] Edit a controlled document during the review route
- [x] Edit a controlled document during the approval route

For all cases, remember that the security has to be set properly for the user to even be able to see the edit form & checkout document action.  In the case of the form, this can be done (for Documentum) in the wizard admin.

@dgrumieaux @benallenallen - this issue is only High Priority if our current HPI/AW client on Documentum needs any of the above cases.  Once those are checked off, we can remove the High Priority label.

**Comment by dgrumieaux** [comment]
Dctm issues fixed in HPI 11753/OC 10870. Pending edge1 test before considering Dctm items checked on @gsteimer 's previous comment.

**Comment by dgrumieaux** [comment]
First two items in @gsteimer 's comment have been tested in edge1.

**Comment by dgrumieaux** [comment]
Third and fourth items in @gsteimer 's comment have been tested in edge1.

**Comment by dgrumieaux** [comment]
Removing high priority label and unassigning myself.

**Comment by gsteimer** [comment]
Thanks @dgrumieaux!  I'll assign myself and test out Alfresco when I get some time.  If it all works, I'll check them off and close.  Otherwise, I'll put the Alfresco label on this issue.

**Comment by gsteimer** [comment]
@dgrumieaux @benallenallen - yeah, editing during workflow on Alfresco... not so much.  Basically, when you try to edit, the resume form dialog just closes.  Oddly there's no error (at least that I saw) in the alfresco log.  

Looking at the permissions, I'm thinking we should remove the Write permissions from the `wizard_form_in_review` permissionGroup:

``` XML
<permissionGroup name="wizard_form_in_review" expose="false">
    <includePermissionGroup type="sys:base" permissionGroup="Read"/>
    <includePermissionGroup type="sys:base" permissionGroup="Write"/>
    <includePermissionGroup type="sys:base" permissionGroup="AddChildren" />
    <includePermissionGroup type="cm:lockable" permissionGroup="CheckOut" />
    <includePermissionGroup type="cm:workingcopy" permissionGroup="CheckIn" />
    <includePermissionGroup type="cm:workingcopy" permissionGroup="CancelCheckOut" />
</permissionGroup>
```

I'm thinking the one above should have no write permissions, and then we should create a new `wizard_form_in_review_edit` permission set to use when we eventually support this.

**Comment by mikeblum** [comment]
editing a form during review and approval routes works as well as forms with Supporting docs. Next to test will be controlled docs.

**Comment by gsteimer** [comment]
@mikeblum - once this is in place, can you make the default permissions so that `wizard_form_in_review` and `controlled_doc_in_review` give Write permissions?  I still want Pending Approval to be locked down by default.

**Comment by gsteimer** [comment]
Actually - I take that back - we don't want to edit the existing permission sets, we want new ones.  This would mirror how we use ACLs in Documentum.  We're going to want two new permission groups: `wizard_form_in_review_edit` (actually - this already exists, I just checked) and `controlled_doc_in_review_edit`.   We would do the same thing for `wizard_form_pending_approval_edit` (exists) and `controlled_doc_pending_approval_edit`.  

All of the above except `wizard_form_in_review_edit` would just be there for clients to use if needed.

**Comment by mikeblum** [comment]
Wizard_contributors and Wizard_administrators now have the powers to version a controlled document during Pending Approval and In Review but that controlled doc in both routes falls back to Draft and the next minor version...

**Comment by gsteimer** [comment]
@mikeblum - the default should be that _nobody_ can version a form or document in Pending Approval.  This is the most common scenario from a compliance perspective and one that we demo all the time.

@benallenallen - feel free to weigh in if you disagree.

**Comment by mikeblum** [comment]
It appears when a tsg controlled document is checked-in, the draft aspect is applied along with the current pendingApproval aspect:

![selection_026](https://cloud.githubusercontent.com/assets/3905463/8854456/9d9b6006-3125-11e5-92b3-1d88bc55c750.png)

This happens right after the AlfrescoEmb serviceRegistry.getCheckOutCheckInService().checkin call.

**Comment by gsteimer** [comment]
@benallenallen @dgrumieaux - could this be because when an Effective doc is checked in, we want it to be Draft?

What I'm wondering is - can we put something in there (wherever it's applying the Draft aspect upon checkin) to say it should only do that if this is a brand new node?  I.e. - when checking in 1.1 from 1.0, Effective, the 1.1 should be a new Node in Draft.  However, going from 1.2 Pending Approval to 1.3 Pending Approval should be fine...

**Comment by gsteimer** [comment]
Closing this - @grahamsinger verified that the remaining two items (edit controlled doc in review / approval) now works with Chain Versionable in Alfresco.  If your project is still using the legacy pre-CVN code, there's a fix on project Turntables UAT branch.
