### ISSUE TITLE
Approval Route Complete Email Lists Document Titles instead of Object Name

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#87]
See the screenshot below - it looks like the approval route complete email is listing out the document titles rather than the object_name.  The object names of the documents attached below are TSG-111 and TSG-112.

![image](https://cloud.githubusercontent.com/assets/1377228/4065239/e640700a-2e18-11e4-88c9-6d8d335891e2.png)

Note that this was on Documentum.  I'm not sure how this is working on Alfresco, since controlled docs in Alfresco don't have a title attribute by default.

In any case, this should be fixed and tested for both Documentum and Alfresco.

**Comment by gsteimer** [comment]
@dgrumieaux @mikeblum - needed for our current client

**Comment by ghost** [comment]
The email template is fixed to now use the object name instead of the title.
CR - Dan G.
OC - 11026
