### ISSUE TITLE
Not Retrieving Parent form for Controlled Docs

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#89]
This is potentially related to #42 

Seen on both release1 and edge1 (Documentum) - it looks like for some reason when a document gets to Approved / Effective, the related objects in the stage cannot find the form parent in the `aw_rel_workflow_doc` relationship.  Here's how the relationship is configured in the stage config:

![screenhunter_245 sep 15 15 26](https://cloud.githubusercontent.com/assets/1377228/4278267/a77d8526-3d16-11e4-9774-952530b6b767.jpg)

I can see the relationship from the form:

![screenhunter_244 sep 15 15 15](https://cloud.githubusercontent.com/assets/1377228/4278279/b9b7be78-3d16-11e4-8cda-c0e9c4cbe8f0.jpg)

But not from the document:

![screenhunter_243 sep 15 15 12](https://cloud.githubusercontent.com/assets/1377228/4278285/bf1be7ea-3d16-11e4-8e99-3eb60c90ff08.jpg)
![screenhunter_242 sep 15 15 12](https://cloud.githubusercontent.com/assets/1377228/4278288/c13ab538-3d16-11e4-9761-2802b822333d.jpg)

Interestingly enough, I **can** see the relationship from the document when the doc is in Draft.

**Comment by dgrumieaux** [comment]
Turns out the relationship name is actually **aw_rel_workflow_document**. Changing the edge1 configs to use this relationship name makes the relationship appear all the time.

**Comment by dgrumieaux** [comment]
Removing the issue label and closing.

**Comment by gsteimer** [comment]
Huh, weird - I wonder how the relationship was displaying at all then...

**Comment by dgrumieaux** [comment]
Yeah, that confused me too.
